// server.js —— Express 静态托管 + Socket.IO 契约层。
// 会话与 socket 解耦：CodexSession 挂在服务端，事件 io.emit 广播（多设备同看）。
// Generated by claude-sonnet-4-6
import dotenv from 'dotenv';
import { createServer } from 'node:http';
import { statSync, existsSync, mkdirSync, readFileSync } from 'node:fs';
import { homedir } from 'node:os';
import { join } from 'node:path';
import { execSync } from 'node:child_process';
import { createHash, randomBytes, timingSafeEqual } from 'node:crypto';
import { isIP } from 'node:net';
import { watch } from 'node:fs';
import express from 'express';
import compression from 'compression';
import { Server } from 'socket.io';
import { ThreadRuntime } from './thread-runtime.js';
import { ThreadRegistry } from './thread-registry.js';
import { AppServerHost } from './app-server-host.js';
import { MessageReceiptLedger } from './message-receipt-ledger.js';
import { NeedsYouRegistry } from './needs-you-registry.js';
import { resolveInputParts } from './input-parts.js';
import { maskToken, sanitize, sanitizePath } from './sanitizer.js';
import { writeOwnerOnlyFile, appendOwnerOnlyFile } from './file-security.js';
import { appendJsonlAuditRecord } from './audit-log.js';
import { createPushSender } from './push-sender.js';
import { isPublicEndpointHostname, isPublicIpAddress } from './network-address.js';
import { validateAttachments, saveAttachments, pruneExpiredUploads } from './uploads.js';
import { buildStatusLine } from './statusline.js';
import { sanitizeTurnOverrides } from './public/js/cli-settings.js';
import webpush from 'web-push';
import {
  isDeviceTrusted,
  addPendingDevice,
  getLatestPendingDevice,
  approveDevice,
  denyDevice,
  getPendingDevices,
  getTrustedDeviceTokens,
} from './devices.js';
import {
  isLocalAccess,
  normalizeAddress,
  resolveListenHost,
  parseGatewaySecurityPolicy,
  evaluateTransportSecurity,
  evaluateSocketHandshakeSecurity,
} from './server-security.js';
import { resolveWorkdirAllowlist } from './workdir-allowlist.js';
import { searchFiles } from './file-search.js';
import { listGitChanges, readGitDiff } from './git-workspace.js';
import { normalizeThreadHistoryMessages } from './thread-history.js';

dotenv.config();
for (const k of Object.keys(process.env)) {
  if (process.env[k] === '') delete process.env[k];
}

const {
  AUTH_TOKEN = '',
  IDLE_TIMEOUT_MS = 600000
} = process.env;

let WORK_DIR = process.env.WORK_DIR || homedir();
let workDirs = [];
const rawPort = Number(process.env.PORT);
const PORT = Number.isInteger(rawPort) && rawPort >= 0 ? rawPort : 3001;
const shouldStartServer = process.env.CODEX_SERVER_NO_START !== '1';
let HOST;
try {
  HOST = resolveListenHost({ env: process.env, authToken: AUTH_TOKEN });
} catch (err) {
  console.error(`\n❌ 启动失败：${err.message}\n`);
  process.exit(1);
}
const idleTimeoutMs = Number(IDLE_TIMEOUT_MS) > 0 ? Number(IDLE_TIMEOUT_MS) : 600000;
const GATEWAY_EPOCH = randomBytes(16).toString('hex');
const gatewaySecurityPolicy = parseGatewaySecurityPolicy(process.env);
const HERE = import.meta.dirname;
const DATA_DIR = process.env.CODEX_DATA_DIR || join(HERE, 'data');
const ADMIN_UNLOCK_PHRASE = 'ENABLE ADMIN';
const ADMIN_AUDIT_FILE = join(DATA_DIR, 'admin-audit.jsonl');
const SECURITY_AUDIT_FILE = join(DATA_DIR, 'security-audit.jsonl');
const ADMIN_ENABLED = process.env.CODEX_ADMIN_ENABLED === '1';
const rawAdminUnlockTtlMs = Number(process.env.CODEX_ADMIN_UNLOCK_TTL_MS);
const ADMIN_UNLOCK_TTL_MS = Number.isInteger(rawAdminUnlockTtlMs) && rawAdminUnlockTtlMs > 0
  ? rawAdminUnlockTtlMs
  : 5 * 60 * 1000;
const rawAdminUnlockMaxFailures = Number(process.env.CODEX_ADMIN_UNLOCK_MAX_FAILURES);
const ADMIN_UNLOCK_MAX_FAILURES = Number.isInteger(rawAdminUnlockMaxFailures) && rawAdminUnlockMaxFailures > 0
  ? rawAdminUnlockMaxFailures
  : 5;
const rawAdminUnlockWindowMs = Number(process.env.CODEX_ADMIN_UNLOCK_WINDOW_MS);
const ADMIN_UNLOCK_WINDOW_MS = Number.isInteger(rawAdminUnlockWindowMs) && rawAdminUnlockWindowMs > 0
  ? rawAdminUnlockWindowMs
  : 60_000;
const P3_EXPERIMENTAL_ENABLED = process.env.CODEX_P3_EXPERIMENTAL === '1';
const REMOTE_IMAGE_INPUTS_ENABLED = process.env.CODEX_ALLOW_REMOTE_IMAGES === '1';
const rawPushMaxSubscriptions = Number(process.env.CODEX_PUSH_MAX_SUBSCRIPTIONS);
const PUSH_MAX_SUBSCRIPTIONS = Number.isInteger(rawPushMaxSubscriptions) && rawPushMaxSubscriptions > 0
  ? rawPushMaxSubscriptions
  : 64;
const rawAuthMaxFailures = Number(process.env.CODEX_AUTH_MAX_FAILURES);
const AUTH_MAX_FAILURES = Number.isInteger(rawAuthMaxFailures) && rawAuthMaxFailures > 0
  ? rawAuthMaxFailures
  : 5;
const rawAuthWindowMs = Number(process.env.CODEX_AUTH_WINDOW_MS);
const AUTH_WINDOW_MS = Number.isInteger(rawAuthWindowMs) && rawAuthWindowMs > 0
  ? rawAuthWindowMs
  : 60_000;
const rawSecurityAuditMaxBytes = Number(process.env.CODEX_SECURITY_AUDIT_MAX_BYTES);
const SECURITY_AUDIT_MAX_BYTES = Number.isInteger(rawSecurityAuditMaxBytes) && rawSecurityAuditMaxBytes > 0
  ? rawSecurityAuditMaxBytes
  : 1024 * 1024;
const rawPendingDeviceLimit = Number(process.env.CODEX_PENDING_DEVICE_LIMIT);
const PENDING_DEVICE_LIMIT = Number.isInteger(rawPendingDeviceLimit) && rawPendingDeviceLimit > 0
  ? rawPendingDeviceLimit
  : 32;
const CLIENT_REQUEST_ID_PATTERN = /^[A-Za-z0-9._:-]{1,128}$/;
const DEVICE_TOKEN_PATTERN = /^[A-Za-z0-9._:-]{16,128}$/;
const SOCKET_MAX_HTTP_BUFFER_SIZE = 32 * 1024 * 1024;
const AUTH_SESSION_COOKIE = 'codex_session';
const rawAuthSessionTtlMs = Number(process.env.CODEX_SESSION_TTL_MS);
const AUTH_SESSION_TTL_MS = Number.isInteger(rawAuthSessionTtlMs) && rawAuthSessionTtlMs > 0
  ? rawAuthSessionTtlMs
  : 7 * 24 * 60 * 60 * 1000;
const authSessions = new Map();
let authSessionsPruneTimer = null;
let failureWindowsPruneTimer = null;

function pruneExpiredAuthSessions(now = Date.now()) {
  for (const [key, session] of authSessions) {
    if (session.expiresAt <= now) authSessions.delete(key);
  }
}

// ---- Web Push ----
const VAPID_PUBLIC_KEY  = process.env.VAPID_PUBLIC_KEY  || '';
const VAPID_PRIVATE_KEY = process.env.VAPID_PRIVATE_KEY || '';
const VAPID_SUBJECT     = process.env.VAPID_SUBJECT     || '';
const pushEnabled = !!(VAPID_PUBLIC_KEY && VAPID_PRIVATE_KEY && VAPID_SUBJECT);
if (pushEnabled) webpush.setVapidDetails(VAPID_SUBJECT, VAPID_PUBLIC_KEY, VAPID_PRIVATE_KEY);
const sendPushNotification = createPushSender({
  generateRequestDetails: webpush.generateRequestDetails,
});

const PUSH_SUB_FILE = join(DATA_DIR, 'push-subscriptions.json');
let pushSubscriptions = [];
try {
  const raw = JSON.parse(readFileSync(PUSH_SUB_FILE, 'utf8'));
  const records = Array.isArray(raw) ? raw : (raw?.endpoint ? [raw] : []);
  pushSubscriptions = records.map(normalizeStoredPushSubscription).filter(Boolean);
} catch {}

function persistPushSubs(subscriptions = pushSubscriptions) {
  try {
    writeOwnerOnlyFile(PUSH_SUB_FILE, JSON.stringify(subscriptions));
    return true;
  } catch {
    return false;
  }
}

function removePushSubscriptionsForDevice(deviceToken) {
  const remaining = pushSubscriptions.filter(subscription => subscription.deviceToken !== deviceToken);
  if (remaining.length === pushSubscriptions.length) return false;
  pushSubscriptions = remaining;
  if (!persistPushSubs()) console.error('[push] 无法持久化已撤销设备的订阅移除');
  return true;
}

async function pushNotify(notification) {
  if (!pushEnabled || pushSubscriptions.length === 0) return;
  const eligible = pushSubscriptions.filter(subscription => (
    isDeviceTrusted(subscription.deviceToken)
    || getSocketsByDeviceToken(subscription.deviceToken).some(socket => socket.deviceApproved === true)
  ));
  if (eligible.length !== pushSubscriptions.length) {
    const removed = pushSubscriptions.length - eligible.length;
    pushSubscriptions = eligible;
    const persisted = persistPushSubs();
    appendSecurityAudit({
      event: 'push_subscription',
      action: 'prune',
      outcome: persisted ? 'success' : 'error',
      reasonCode: 'device_untrusted',
      removed,
    });
  }
  if (eligible.length === 0) return;
  const payload = JSON.stringify(notification);
  const expired = [];
  await Promise.all(eligible.map(sub =>
    sendPushNotification(sub, payload).catch(e => {
      if (e.statusCode === 410 || e.statusCode === 404) expired.push(sub.endpoint);
    })
  ));
  if (expired.length) {
    pushSubscriptions = pushSubscriptions.filter(s => !expired.includes(s.endpoint));
    if (!persistPushSubs()) console.error('[push] 无法持久化过期订阅清理');
  }
}

export function pushDecision(envelope) {
  if (!envelope || typeof envelope.type !== 'string') return null;
  if (envelope.type === 'approval_request') {
    return needsYouPush(envelope, 'Codex 待审批', '有操作等待审批');
  }
  if (envelope.type === 'user_input_request') {
    return needsYouPush(envelope, 'Codex 需要人到场', '有问题等待回答');
  }
  if (envelope.type === 'approval_revoked') return null;
  if (envelope.type === 'result' || envelope.type === 'error') {
    const status = envelope.payload?.ok ? '完成' : '出错';
    return {
      title: `Codex ${status}`,
      body: pushText(envelope.payload?.status || envelope.payload?.message || '任务已完成'),
    };
  }
  return null;
}

function needsYouPush(envelope, title, body) {
  const needId = typeof envelope.payload?.needId === 'string' ? envelope.payload.needId : null;
  const threadId = envelope.sessionId || envelope.payload?.threadId || null;
  const data = {};
  if (needId) data.needId = needId;
  if (threadId) data.threadId = threadId;
  if (threadId) {
    const params = new URLSearchParams({ thread: threadId });
    if (needId) params.set('need', needId);
    data.url = `/?${params.toString().replace(/\+/g, '%20')}`;
  }
  return {
    title,
    body,
    tag: needId ? `need:${needId}` : 'ccm-needs-you',
    data,
  };
}

function pushText(value) {
  const text = typeof value === 'string' ? value : String(value ?? '');
  return text.length > 180 ? `${text.slice(0, 180)} ...` : text;
}

async function canonicalAttachmentFingerprints(attachments) {
  const result = [];
  for (const attachment of (attachments || [])) {
    // Yield to event loop between attachments to avoid blocking on large files
    if (attachment.data && attachment.data.length > 1_000_000) await new Promise(resolve => setImmediate(resolve));
    result.push({
      name: attachment.name,
      mimeType: attachment.mimeType,
      decodedSha256: createHash('sha256')
        .update(Buffer.from(attachment.data, 'base64'))
        .digest('hex'),
    });
  }
  return result;
}

function canonicalInputPartFingerprints(parts) {
  return (parts || []).map(part => {
    if (part?.kind === 'mention') return { kind: 'mention', path: part.path };
    if (part?.kind === 'skill') return { kind: 'skill', name: part.name, path: part.path };
    if (part?.kind === 'imageUrl') {
      return { kind: 'imageUrl', url: part.url, detail: part.detail ?? null };
    }
    return { kind: part?.kind ?? null };
  });
}
// 仅 app-server 后端（长驻 JSON-RPC，原生流式/审批）
const SessionClass = ThreadRuntime;

// ---- 启动预检 ----
const versions = { codex: 'unknown' };

function buildInitPayload({ sessionId = null, instanceId = null, cwd = WORK_DIR } = {}) {
  return {
    sessionId,
    instanceId,
    gatewayEpoch: GATEWAY_EPOCH,
    cwd,
    workDirs,
    versions,
    features: {
      admin: ADMIN_ENABLED,
      labs: P3_EXPERIMENTAL_ENABLED,
    },
  };
}

function preflight() {
  const fail = msg => {
    console.error(`\n❌ 启动失败：${msg}\n`);
    process.exit(1);
  };
  try {
    initializeWorkDirs();
  } catch (err) {
    fail(err.message);
  }

  let codexBin = process.env.CODEX_BIN || '';
  if (!codexBin) {
    try {
      codexBin = execSync('which codex', { encoding: 'utf8' }).trim();
    } catch {
      fail('未找到 codex 命令。请先安装 Codex CLI，或在 .env 中用 CODEX_BIN 指定路径');
    }
  }
  try {
    statSync(codexBin);
  } catch {
    fail(`CODEX_BIN 指向的文件不存在：${codexBin}`);
  }
  try {
    versions.codex = execSync(`"${codexBin}" --version`, { encoding: 'utf8' }).trim();
  } catch { /* 非致命 */ }

  console.log(`\n✅ Codex Chat Mobile 启动`);
  console.log(`   WORK_DIR: ${WORK_DIR}`);
  if (workDirs.length > 1) console.log(`   WORK_DIRS: ${workDirs.length} 个工作区`);
  console.log(`   CODEX_BIN: ${codexBin}`);
  console.log(`   HOST: ${HOST}`);
  console.log(`   PORT: ${PORT}`);
  console.log(`   BACKEND: app-server`);
  if (AUTH_TOKEN) console.log(`   AUTH_TOKEN: ${maskToken(AUTH_TOKEN)}`);
  else console.log(`   AUTH_TOKEN: （未设置，仅允许 loopback Host + loopback socket）`);
  console.log('');

  return codexBin;
}

function initializeWorkDirs() {
  const resolved = resolveWorkdirAllowlist({
    workDir: WORK_DIR,
    extra: process.env.WORK_DIRS || '',
    baseDir: HERE,
  });
  WORK_DIR = resolved.workDir;
  workDirs = resolved.workDirs;
  for (const warning of resolved.warnings) console.warn(`⚠️  ${warning}`);
}
const codexBin = shouldStartServer ? preflight() : (process.env.CODEX_BIN || 'codex');

// ---- HTTP ----
const app = express();
app.use(compression());
app.use((req, res, next) => {
  const decision = evaluateTransportSecurity({
    remoteAddress: req.socket?.remoteAddress || req.ip,
    hostHeader: req.headers.host,
    socketEncrypted: req.socket?.encrypted === true,
    forwardedProtoHeader: req.headers['x-forwarded-proto'],
  }, gatewaySecurityPolicy);
  req.codexGatewaySecurity = decision;
  if (decision.ok) return next();
  return res.status(426).json({
    status: 'secure_transport_required',
    errorCode: decision.reason,
  });
});
app.use((_req, res, next) => {
  res.setHeader('Content-Security-Policy', [
    "default-src 'self'",
    "script-src 'self'",
    "style-src 'self' 'unsafe-inline'",
    "img-src 'self' data:",
    "connect-src 'self' ws: wss:",
    "font-src 'self'",
    "frame-ancestors 'none'"
  ].join('; '));
  res.setHeader('X-Frame-Options', 'DENY');
  res.setHeader('X-Content-Type-Options', 'nosniff');
  res.setHeader('Referrer-Policy', 'no-referrer');
  next();
});

const clientIp = v => normalizeAddress(v);
const authFailureWindows = new Map();
const adminUnlockFailureWindows = new Map();

function pruneExpiredFailureWindows(now = Date.now()) {
  for (const [key, value] of authFailureWindows) {
    if (value.resetAt <= now) authFailureWindows.delete(key);
  }
  for (const [key, value] of adminUnlockFailureWindows) {
    if (value.resetAt <= now) adminUnlockFailureWindows.delete(key);
  }
}

function recordAuthFailure(address, now = Date.now()) {
  const key = clientIp(address) || 'unknown';
  let window = authFailureWindows.get(key);
  if (!window || window.resetAt <= now) {
    window = { count: 0, resetAt: now + AUTH_WINDOW_MS };
  }
  window.count += 1;
  authFailureWindows.set(key, window);
  if (authFailureWindows.size > 10_000) pruneExpiredFailureWindows(now);
  const rateLimited = window.count > AUTH_MAX_FAILURES;
  return {
    rateLimited,
    shouldAudit: !rateLimited || window.count === AUTH_MAX_FAILURES + 1,
    count: window.count,
    resetAt: window.resetAt,
  };
}

function adminUnlockFailureKey(socket) {
  const deviceToken = socket.handshake.auth?.deviceToken;
  if (typeof deviceToken === 'string' && deviceToken) return `device:${securityRef(deviceToken)}`;
  return `ip:${clientIp(socket.handshake.address) || 'unknown'}`;
}

function readAdminUnlockFailureWindow(socket, now = Date.now()) {
  const key = adminUnlockFailureKey(socket);
  let window = adminUnlockFailureWindows.get(key);
  if (!window || window.resetAt <= now) {
    window = { count: 0, resetAt: now + ADMIN_UNLOCK_WINDOW_MS };
    adminUnlockFailureWindows.set(key, window);
  }
  return { key, window };
}

function recordAdminUnlockFailure(socket, now = Date.now()) {
  const state = readAdminUnlockFailureWindow(socket, now);
  state.window.count += 1;
  return state;
}

function adminUnlockRateLimit(socket, now = Date.now()) {
  const state = readAdminUnlockFailureWindow(socket, now);
  if (state.window.count < ADMIN_UNLOCK_MAX_FAILURES) return null;
  return { retryAfterMs: Math.max(1, state.window.resetAt - now) };
}

function appendSecurityAudit(entry) {
  try {
    appendJsonlAuditRecord(SECURITY_AUDIT_FILE, entry, {
      maxBytes: SECURITY_AUDIT_MAX_BYTES,
    });
  } catch {
    // Security logging must not expose secrets or crash the authentication path.
  }
}

function tokenMatches(got) {
  if (!AUTH_TOKEN || typeof got !== 'string') return false;
  const a = Buffer.from(got), b = Buffer.from(AUTH_TOKEN);
  return a.length === b.length && timingSafeEqual(a, b);
}

function authSessionKey(token) {
  return createHash('sha256').update(token).digest('hex');
}

function securityRef(value) {
  if (typeof value !== 'string' || !value) return null;
  return createHash('sha256').update(value).digest('hex').slice(0, 16);
}

function cookieValue(cookieHeader, name) {
  if (typeof cookieHeader !== 'string') return '';
  for (const part of cookieHeader.split(';')) {
    const [rawName, ...rawValue] = part.trim().split('=');
    if (rawName !== name) continue;
    try {
      return decodeURIComponent(rawValue.join('='));
    } catch {
      return '';
    }
  }
  return '';
}

function readAuthSession(cookieHeader, now = Date.now()) {
  const token = cookieValue(cookieHeader, AUTH_SESSION_COOKIE);
  if (!token) return null;
  const key = authSessionKey(token);
  const session = authSessions.get(key);
  if (!session) return null;
  if (session.expiresAt <= now) {
    authSessions.delete(key);
    return null;
  }
  return { ...session, key };
}

function issueAuthSession(deviceToken, now = Date.now()) {
  const token = randomBytes(32).toString('base64url');
  const key = authSessionKey(token);
  const session = {
    deviceToken,
    createdAt: now,
    expiresAt: now + AUTH_SESSION_TTL_MS,
  };
  authSessions.set(key, session);
  return { token, key, ...session };
}

function revokeAuthSessionsForDevice(deviceToken) {
  let revoked = 0;
  for (const [key, session] of authSessions) {
    if (session.deviceToken !== deviceToken) continue;
    authSessions.delete(key);
    revoked += 1;
  }
  return revoked;
}

function sessionCookie(token, request, { clear = false } = {}) {
  const attributes = [
    `${AUTH_SESSION_COOKIE}=${clear ? '' : encodeURIComponent(token)}`,
    'Path=/',
    'HttpOnly',
    'SameSite=Strict',
    clear ? 'Max-Age=0' : `Max-Age=${Math.floor(AUTH_SESSION_TTL_MS / 1000)}`,
  ];
  if (request.codexGatewaySecurity?.secure) attributes.push('Secure');
  return attributes.join('; ');
}

async function httpAuth(req, res, next) {
  const session = readAuthSession(req.headers.cookie);
  if (session) req.authSession = session;
  if (!AUTH_TOKEN || session || tokenMatches(req.headers['x-auth-token'])) return next();
  return res.status(401).json({ status: 'unauthorized' });
}

function noTokenLocalOnly(req, res, next) {
  if (AUTH_TOKEN) return next();
  if (isLocalAccess({ remoteAddress: req.socket?.remoteAddress || req.ip, hostHeader: req.headers.host })) return next();
  return res.status(403).json({ status: 'local_access_only' });
}

function approvedPushDevice(req, res, next) {
  if (!pushEnabled) return next();
  const deviceToken = req.headers['x-device-token'];
  const approved = typeof deviceToken === 'string'
    && DEVICE_TOKEN_PATTERN.test(deviceToken)
    && (
      isDeviceTrusted(deviceToken)
      || getSocketsByDeviceToken(deviceToken).some(socket => socket.deviceApproved === true)
    );
  if (!approved) return res.status(403).json({ error: 'device_not_approved' });
  req.deviceToken = deviceToken;
  return next();
}

function normalizePushSubscription(body) {
  if (typeof body?.endpoint !== 'string' || body.endpoint.length > 2048) return null;
  let endpoint;
  try {
    endpoint = new URL(body.endpoint);
  } catch {
    return null;
  }
  if (endpoint.protocol !== 'https:' || endpoint.username || endpoint.password) return null;
  if (!isPublicEndpointHostname(endpoint.hostname)) return null;
  if (isIP(endpoint.hostname) && !isPublicIpAddress(endpoint.hostname)) return null;
  const p256dh = body.keys?.p256dh;
  const auth = body.keys?.auth;
  if (
    typeof p256dh !== 'string'
    || p256dh.length < 1
    || p256dh.length > 256
    || typeof auth !== 'string'
    || auth.length < 1
    || auth.length > 128
  ) return null;
  return {
    endpoint: endpoint.href,
    keys: { p256dh, auth },
  };
}

function normalizeStoredPushSubscription(value) {
  if (typeof value?.deviceToken !== 'string' || !DEVICE_TOKEN_PATTERN.test(value.deviceToken)) return null;
  const subscription = normalizePushSubscription(value);
  if (!subscription) return null;
  const now = Date.now();
  return {
    deviceToken: value.deviceToken,
    ...subscription,
    createdAt: Number.isFinite(value.createdAt) ? value.createdAt : now,
    updatedAt: Number.isFinite(value.updatedAt) ? value.updatedAt : now,
  };
}

app.use(noTokenLocalOnly);
app.use(express.static(join(HERE, 'public'), {
  setHeaders: (res, filePath) => {
    if (filePath.endsWith('.html')) res.setHeader('Cache-Control', 'no-store');
    if (filePath.endsWith('/js/sw.js')) res.setHeader('Service-Worker-Allowed', '/');
  }
}));

app.get('/health', httpAuth, (_req, res) => {
  res.json({
    status: 'ok',
    sessionId: null,
    busy: [...agents.values()].some(a => a.busy),
    sessionState: null,
    versions,
    timestamp: Date.now()
  });
});

app.post('/auth/session', (req, res) => {
  const deviceToken = req.headers['x-device-token'];
  if (!AUTH_TOKEN || !tokenMatches(req.headers['x-auth-token'])) {
    const failure = recordAuthFailure(req.socket?.remoteAddress || req.ip);
    if (failure.shouldAudit) {
      appendSecurityAudit({
        event: 'session_issue',
        outcome: failure.rateLimited ? 'rate_limited' : 'denied',
        ip: clientIp(req.socket?.remoteAddress || req.ip),
        ...(failure.rateLimited ? { attempts: failure.count, resetAt: failure.resetAt } : {}),
      });
    }
    return res.status(failure.rateLimited ? 429 : 401).json({
      status: failure.rateLimited ? 'rate_limited' : 'unauthorized',
    });
  }
  if (typeof deviceToken !== 'string' || !DEVICE_TOKEN_PATTERN.test(deviceToken)) {
    return res.status(400).json({ error: 'invalid_device_token' });
  }
  const session = issueAuthSession(deviceToken);
  res.setHeader('Cache-Control', 'no-store');
  res.setHeader('Set-Cookie', sessionCookie(session.token, req));
  appendSecurityAudit({
    event: 'session_issue',
    outcome: 'success',
    deviceRef: session.key.slice(0, 16),
    ip: clientIp(req.socket?.remoteAddress || req.ip),
  });
  return res.status(201).json({ ok: true, expiresAt: session.expiresAt });
});

app.delete('/auth/session', httpAuth, (req, res) => {
  const session = req.authSession;
  if (!session) return res.status(400).json({ error: 'session_cookie_required' });
  authSessions.delete(session.key);
  res.setHeader('Set-Cookie', sessionCookie('', req, { clear: true }));
  appendSecurityAudit({
    event: 'session_revoke',
    outcome: 'success',
    deviceRef: session.key.slice(0, 16),
    ip: clientIp(req.socket?.remoteAddress || req.ip),
  });
  for (const socket of io.sockets.sockets.values()) {
    if (socket.data.authSessionKey === session.key) socket.disconnect(true);
  }
  return res.status(204).end();
});

// Push endpoints
app.get('/push/vapid-public-key', (_req, res) => {
  if (!pushEnabled) return res.status(503).json({ error: 'push not configured' });
  res.json({ key: VAPID_PUBLIC_KEY });
});
app.post('/push/subscribe', httpAuth, approvedPushDevice, express.json({ limit: '4kb' }), (req, res) => {
  if (!pushEnabled) return res.status(503).json({ error: 'push not configured' });
  const normalized = normalizePushSubscription(req.body);
  if (!normalized) return res.status(400).json({ error: 'invalid_subscription' });
  const existingForDevice = pushSubscriptions.find(s => s.deviceToken === req.deviceToken);
  if (!existingForDevice && pushSubscriptions.length >= PUSH_MAX_SUBSCRIPTIONS) {
    return res.status(429).json({ error: 'subscription_limit' });
  }
  const previous = pushSubscriptions.find(s => (
    s.endpoint === normalized.endpoint || s.deviceToken === req.deviceToken
  ));
  const now = Date.now();
  const subscription = {
    deviceToken: req.deviceToken,
    endpoint: normalized.endpoint,
    keys: normalized.keys,
    createdAt: Number.isFinite(previous?.createdAt) ? previous.createdAt : now,
    updatedAt: now,
  };
  const nextSubscriptions = pushSubscriptions.filter(s => (
    s.endpoint !== normalized.endpoint && s.deviceToken !== req.deviceToken
  ));
  nextSubscriptions.push(subscription);
  if (!persistPushSubs(nextSubscriptions)) {
    appendSecurityAudit({
      event: 'push_subscription',
      action: 'subscribe',
      outcome: 'error',
      reasonCode: 'persist_failed',
      deviceRef: securityRef(req.deviceToken),
    });
    return res.status(500).json({ error: 'subscription_persist_failed' });
  }
  pushSubscriptions = nextSubscriptions;
  appendSecurityAudit({
    event: 'push_subscription',
    action: 'subscribe',
    outcome: 'success',
    deviceRef: securityRef(req.deviceToken),
  });
  res.json({ ok: true });
});

const httpServer = createServer(app);
const io = new Server(httpServer, {
  maxHttpBufferSize: SOCKET_MAX_HTTP_BUFFER_SIZE,
  perMessageDeflate: { threshold: 1024 },
  allowRequest: (request, callback) => {
    const decision = evaluateSocketHandshakeSecurity({
      remoteAddress: request.socket?.remoteAddress,
      hostHeader: request.headers.host,
      socketEncrypted: request.socket?.encrypted === true,
      forwardedProtoHeader: request.headers['x-forwarded-proto'],
      originHeader: request.headers.origin,
    }, gatewaySecurityPolicy);
    request.codexGatewaySecurity = decision;
    callback(decision.ok ? null : decision.reason, decision.ok);
  },
});

// ---- 设备审批辅助函数 ----
function getSocketsByDeviceToken(deviceToken) {
  const list = [];
  if (!deviceToken) return list;
  for (const socket of io.sockets.sockets.values()) {
    if (socket.handshake.auth?.deviceToken === deviceToken) list.push(socket);
  }
  return list;
}

function unlockSocket(socket) {
  if (socket.deviceApproved) return;
  socket.deviceApproved = true;
  const deviceToken = socket.handshake.auth?.deviceToken;
  socket.emit('agent:event', {
    seq: 0, epoch: 'server', sessionId: null, ts: Date.now(),
    type: 'device_status', payload: { status: 'approved', deviceId: deviceToken }
  });
  const va = routeInstance(socket.data.viewingInstanceId);
  socket.emit('agent:event', {
    seq: 0,
    epoch: 'server',
    sessionId: va?.sessionId ?? null,
    instanceId: va?.instanceId ?? null,
    ts: Date.now(),
    type: 'init',
    payload: buildInitPayload(va
      ? { sessionId: va.sessionId, instanceId: va.instanceId, cwd: va.cwd }
      : {}),
  });
  if (va) sendActiveStatus(socket, 'device_unlocked');
  broadcastPendingDevices();
  scheduleStatusRefresh();
}

function unlockDeviceSockets(deviceToken) {
  for (const socket of getSocketsByDeviceToken(deviceToken)) unlockSocket(socket);
}

function approveDeviceAccess(deviceToken, {
  persistTrust = false,
  source = 'unknown',
  actorToken = null,
} = {}) {
  if (typeof deviceToken !== 'string' || !deviceToken) return false;
  if (persistTrust && !approveDevice(deviceToken)) {
    appendSecurityAudit({
      event: 'device_access',
      action: 'approve',
      outcome: 'failure',
      reason: 'persist_failed',
      source,
      subjectRef: securityRef(deviceToken),
      actorRef: securityRef(actorToken),
    });
    return false;
  }
  if (persistTrust) trustedDeviceSnapshot.add(deviceToken);
  unlockDeviceSockets(deviceToken);
  appendSecurityAudit({
    event: 'device_access',
    action: 'approve',
    outcome: 'success',
    source,
    subjectRef: securityRef(deviceToken),
    actorRef: securityRef(actorToken),
  });
  return true;
}

function disconnectDeviceSockets(deviceToken, { preserveLocalSockets = false } = {}) {
  for (const socket of getSocketsByDeviceToken(deviceToken)) {
    if (preserveLocalSockets && socket.request?.codexGatewaySecurity?.local === true) continue;
    socket.emit('agent:event', {
      seq: 0, epoch: 'server', sessionId: null, ts: Date.now(),
      type: 'device_status', payload: { status: 'denied', deviceId: deviceToken }
    });
    socket.disconnect(true);
  }
}

function revokeDeviceAccess(deviceToken, {
  removeTrust = false,
  preserveLocalSockets = false,
  source = 'unknown',
  actorToken = null,
} = {}) {
  if (typeof deviceToken !== 'string' || !deviceToken) return false;
  const trustPersisted = !removeTrust || denyDevice(deviceToken);
  if (removeTrust && trustPersisted) trustedDeviceSnapshot.delete(deviceToken);
  for (const socket of getSocketsByDeviceToken(deviceToken)) {
    if (preserveLocalSockets && socket.request?.codexGatewaySecurity?.local === true) continue;
    socket.deviceApproved = false;
  }
  const revokedSessions = revokeAuthSessionsForDevice(deviceToken);
  const pushRemoved = removePushSubscriptionsForDevice(deviceToken);
  disconnectDeviceSockets(deviceToken, { preserveLocalSockets });
  appendSecurityAudit({
    event: 'device_access',
    action: 'deny',
    outcome: trustPersisted ? 'success' : 'partial',
    ...(trustPersisted ? {} : { reason: 'persist_failed' }),
    source,
    subjectRef: securityRef(deviceToken),
    actorRef: securityRef(actorToken),
    revokedSessions,
    pushRemoved,
  });
  return trustPersisted;
}

function pendingDevicesPayload() {
  return { devices: getPendingDevices().map(d => ({ deviceId: d.deviceToken, ip: d.ip, userAgent: d.userAgent, ts: d.ts })) };
}

function broadcastPendingDevices() {
  const payload = pendingDevicesPayload();
  for (const socket of io.sockets.sockets.values()) {
    if (socket.deviceApproved === true) {
      socket.emit('agent:event', {
        seq: 0, epoch: 'server', sessionId: null, ts: Date.now(),
        type: 'pending_devices', payload
      });
    }
  }
}

const TRUSTED_DEVICES_FILE = join(DATA_DIR, 'trusted-devices.json');
const PENDING_DEVICES_FILE = join(DATA_DIR, 'pending-devices.json');
let trustedDevicesWatcher = null;
let trustedDevicesReconcileTimer = null;
let trustedDeviceSnapshot = new Set();

function ensureDeviceFiles() {
  try {
    mkdirSync(DATA_DIR, { recursive: true });
    if (!existsSync(TRUSTED_DEVICES_FILE)) writeOwnerOnlyFile(TRUSTED_DEVICES_FILE, JSON.stringify([], null, 2));
    if (!existsSync(PENDING_DEVICES_FILE)) writeOwnerOnlyFile(PENDING_DEVICES_FILE, JSON.stringify([], null, 2));
  } catch (err) {
    console.error('[devices] 初始化设备认证文件失败:', err.message);
  }
}

function reconcileTrustedDeviceSockets() {
  const latestTrustedDevices = getTrustedDeviceTokens();
  const approvedDeviceTokens = new Set();
  const revokedDeviceTokens = new Set();
  for (const deviceToken of trustedDeviceSnapshot) {
    if (!latestTrustedDevices.has(deviceToken)) revokedDeviceTokens.add(deviceToken);
  }
  trustedDeviceSnapshot = latestTrustedDevices;
  for (const socket of io.sockets.sockets.values()) {
    const deviceToken = socket.handshake.auth?.deviceToken;
    if (typeof deviceToken !== 'string' || !DEVICE_TOKEN_PATTERN.test(deviceToken)) continue;
    const trusted = latestTrustedDevices.has(deviceToken);
    if (socket.deviceApproved === false && trusted) {
      approvedDeviceTokens.add(deviceToken);
      continue;
    }
    const local = socket.request?.codexGatewaySecurity?.local === true;
    if (socket.deviceApproved === true && !local && !trusted) {
      revokedDeviceTokens.add(deviceToken);
    }
  }

  for (const deviceToken of approvedDeviceTokens) {
    console.log(`[devices] 检测到变更，自动解锁设备 ${deviceToken}`);
    approveDeviceAccess(deviceToken, { source: 'trusted_file' });
  }
  for (const deviceToken of revokedDeviceTokens) {
    console.warn(`[devices] 检测到外部撤销，断开设备 ${deviceToken}`);
    revokeDeviceAccess(deviceToken, { source: 'trusted_file', preserveLocalSockets: true });
  }
  broadcastPendingDevices();
}

function scheduleTrustedDeviceReconcile() {
  clearTimeout(trustedDevicesReconcileTimer);
  trustedDevicesReconcileTimer = setTimeout(() => {
    trustedDevicesReconcileTimer = null;
    reconcileTrustedDeviceSockets();
  }, 100);
  trustedDevicesReconcileTimer.unref?.();
}

// 监听状态目录而不是文件 inode，兼容 owner-only 原子 rename 写入。
function startTrustedDevicesWatcher() {
  if (trustedDevicesWatcher) return;
  ensureDeviceFiles();
  trustedDeviceSnapshot = getTrustedDeviceTokens();
  try {
    trustedDevicesWatcher = watch(DATA_DIR, (_eventType, filename) => {
      if (filename && String(filename) !== 'trusted-devices.json') return;
      scheduleTrustedDeviceReconcile();
    });
    trustedDevicesWatcher.on('error', err => {
      console.error('[devices] 监视 trusted-devices.json 失败:', err.message);
    });
    trustedDevicesWatcher.unref?.();
  } catch (err) {
    console.error('[devices] 无法监视 trusted-devices.json:', err.message);
  }
}

function stopTrustedDevicesWatcher() {
  clearTimeout(trustedDevicesReconcileTimer);
  trustedDevicesReconcileTimer = null;
  trustedDevicesWatcher?.close();
  trustedDevicesWatcher = null;
  trustedDeviceSnapshot = new Set();
}

// TTY 回车一键审批
if (shouldStartServer && process.stdin.isTTY) {
  process.stdin.setEncoding('utf8');
  process.stdin.on('data', data => {
    const text = data.trim().toLowerCase();
    const latest = getLatestPendingDevice();
    if (text === '') {
      if (latest) {
        console.log(`\n[TTY] 一键批准最新设备: ${latest}`);
        approveDeviceAccess(latest, { persistTrust: true, source: 'tty' });
        broadcastPendingDevices();
      }
    } else if (text === 'deny') {
      if (latest) {
        console.log(`\n[TTY] 拒绝最新设备: ${latest}`);
        revokeDeviceAccess(latest, { removeTrust: true, source: 'tty' });
        broadcastPendingDevices();
      }
    }
  });
}

// ---- Socket.IO 鉴权 ----
io.use(async (socket, next) => {
  try {
    const suppliedDeviceToken = socket.handshake.auth?.deviceToken;
    const isLocal = socket.request?.codexGatewaySecurity?.local === true;
    let authPassed = false;
    let authSession = null;
    if (!AUTH_TOKEN) {
      authPassed = isLocalAccess({
        remoteAddress: socket.handshake.address,
        hostHeader: socket.handshake.headers.host
      });
    } else if (isLocal && tokenMatches(socket.handshake.auth?.token)) {
      authPassed = true;
    } else {
      authSession = readAuthSession(socket.handshake.headers.cookie);
      if (authSession && authSession.deviceToken === suppliedDeviceToken) authPassed = true;
    }

    if (!authPassed) {
      console.warn(`[conn] ${clientIp(socket.handshake.address)} 握手鉴权失败`);
      const failure = recordAuthFailure(socket.handshake.address);
      if (failure.shouldAudit) {
        appendSecurityAudit({
          event: 'auth_failure',
          outcome: failure.rateLimited ? 'rate_limited' : 'denied',
          ip: clientIp(socket.handshake.address),
          ...(failure.rateLimited ? { attempts: failure.count, resetAt: failure.resetAt } : {}),
        });
      }
      return next(new Error(failure.rateLimited ? 'rate_limited' : 'unauthorized'));
    }
    socket.data.authSessionKey = authSession?.key ?? null;
    if (
      (!isLocal && suppliedDeviceToken === undefined)
      || (
        suppliedDeviceToken !== undefined
        && (
        typeof suppliedDeviceToken !== 'string'
        || !DEVICE_TOKEN_PATTERN.test(suppliedDeviceToken)
        )
      )
    ) {
      return next(new Error('invalid_device_token'));
    }

    if (isLocal) {
      socket.deviceApproved = true;
    } else {
      const deviceToken = suppliedDeviceToken;
      if (isDeviceTrusted(deviceToken)) {
        socket.deviceApproved = true;
      } else {
        const pendingDevices = getPendingDevices();
        if (
          !pendingDevices.some(device => device.deviceToken === deviceToken)
          && pendingDevices.length >= PENDING_DEVICE_LIMIT
        ) {
          return next(new Error('pairing_capacity'));
        }
        socket.deviceApproved = false;
        const ip = clientIp(socket.handshake.address);
        const ua = socket.handshake.headers['user-agent'] || 'Unknown';
        addPendingDevice(deviceToken, { ip, userAgent: ua });
        broadcastPendingDevices();

        console.log('\n==================================================');
        console.log(`📢 [安全] 发现新设备请求接入！`);
        console.log(`   设备 ID: ${deviceToken || '（未提供）'}`);
        console.log(`   来自 IP: ${ip}`);
        console.log(`   User-Agent: ${ua}`);
        if (process.stdin.isTTY) {
          console.log(`   -> 按【回车键】一键同意此设备`);
          console.log(`   -> 输入【deny】拒绝此设备`);
        } else {
          console.log(`   -> node scripts/device.js approve "${deviceToken}"`);
        }
        console.log('==================================================\n');
      }
    }

    return next();
  } catch (e) {
    return next(new Error('unauthorized'));
  }
});

// ---- 会话管理 ----
// 多实例并行：instanceId → ThreadRuntime；所有 runtime 共享一个 AppServerHost。
const agents = new Map();
const threadRegistry = new ThreadRegistry();
const messageReceiptLedger = new MessageReceiptLedger();
const needsYouRegistry = new NeedsYouRegistry();
let appServerHost = null;
let instanceCounter = 0;
const newInstanceId = () => `inst_${++instanceCounter}`;
const instanceRoom = instanceId => `instance:${instanceId}`;

function getAppServerHost() {
  if (!appServerHost) {
    appServerHost = new AppServerHost({
      codexBin,
      cwd: WORK_DIR,
      registry: threadRegistry,
      experimentalApi: P3_EXPERIMENTAL_ENABLED,
      onThreadStatus: change => broadcastHostThreadStatus(change),
      onUnrouted: frame => {
        if (process.env.LOG_STDERR) console.error('[appserver:unrouted]', frame);
      },
    });
  }
  return appServerHost;
}

function setSocketViewingInstance(socket, instanceId) {
  const previous = socket.data.viewingInstanceId;
  if (previous && previous !== instanceId) socket.leave(instanceRoom(previous));
  socket.data.viewingInstanceId = instanceId || null;
  if (instanceId) socket.join(instanceRoom(instanceId));
}

function clearSocketInstanceReferences(instanceId) {
  for (const socket of io.sockets.sockets.values()) {
    if (socket.data.viewingInstanceId === instanceId) setSocketViewingInstance(socket, null);
    if (socket.data.controlInstanceId === instanceId) socket.data.controlInstanceId = null;
  }
}

// 多工作目录路由
const routeCwd = cwd => (typeof cwd === 'string' && workDirs.includes(cwd)) ? cwd : WORK_DIR;

// 实例路由
const resolveInstanceId = id => agents.has(id) ? id : null;
const routeInstance = id => agents.get(resolveInstanceId(id)) ?? null;

function resolveRuntimeTarget({ instanceId, threadId, turnId, requestId } = {}) {
  const target = {};
  if (typeof instanceId === 'string' && instanceId) target.instanceId = instanceId;
  if (typeof threadId === 'string' && threadId) target.threadId = threadId;
  if (typeof turnId === 'string' && turnId) target.turnId = turnId;
  if (requestId !== undefined && requestId !== null) target.requestId = requestId;
  return threadRegistry.resolve(target);
}

function sendActiveStatus(socket, reason = 'connect') {
  const agent = agents.get(socket.data.viewingInstanceId) ?? null;
  if (typeof agent?.statusPayload !== 'function') return;
  socket.emit('agent:event', {
    seq: 0,
    epoch: 'server',
    sessionId: agent.sessionId ?? null,
    instanceId: agent.instanceId,
    ts: Date.now(),
    type: 'status',
    payload: agent.statusPayload(reason)
  });
}

function syncRuntimeIdentity(runtime, envelope) {
  const turnId = envelope?.payload?.turnId;
  if (typeof turnId === 'string' && turnId) {
    threadRegistry.bind(runtime, { turnId });
  }
  if (envelope?.type === 'approval_request' || envelope?.type === 'user_input_request') {
    const requestId = envelope.payload?.approvalId;
    if (requestId !== undefined && requestId !== null) {
      threadRegistry.bind(runtime, { requestId });
    }
  }
  if (envelope?.type === 'approval_revoked') {
    threadRegistry.releaseRequest(runtime, envelope.payload?.approvalId);
  }
  if (envelope?.type === 'result' || (
    envelope?.type === 'status'
    && ['turn_failed', 'turn_interrupted', 'interrupt', 'interrupt_cleared_queue', 'process_exit', 'process_error']
      .includes(envelope.payload?.reason)
  )) {
    threadRegistry.clearTurn(runtime);
  }
}

function broadcastNeedsYouChange(change) {
  if (!change?.need) return;
  for (const socket of io.sockets.sockets.values()) {
    if (socket.deviceApproved !== true) continue;
    socket.emit('agent:event', {
      seq: 0,
      epoch: 'server',
      sessionId: null,
      instanceId: null,
      ts: Date.now(),
      type: 'needs_you_changed',
      payload: { revision: change.revision, need: change.need },
    });
  }
}

function broadcastHostThreadStatus(change) {
  if (!change?.threadId || !change?.status) return;
  for (const socket of io.sockets.sockets.values()) {
    if (socket.deviceApproved !== true) continue;
    socket.emit('agent:event', {
      seq: 0,
      epoch: 'server',
      sessionId: null,
      instanceId: null,
      ts: Date.now(),
      type: 'thread_status',
      payload: { scope: 'host', ...change },
    });
  }
}

function trackNeedsYou(agent, envelope) {
  if (envelope?.type === 'approval_revoked') {
    const closed = needsYouRegistry.close({
      instanceId: agent.instanceId,
      requestId: envelope.payload?.approvalId ?? envelope.payload?.requestId,
    }, { state: 'revoked', reason: 'upstream_resolved' });
    const need = closed.needs[0] || null;
    if (need) envelope.payload = { ...(envelope.payload || {}), needId: need.needId };
    return need ? [{ changed: closed.changed, revision: closed.revision, need }] : [];
  }
  const terminalStatusReason = envelope?.type === 'status'
    && ['turn_failed', 'turn_interrupted', 'interrupt', 'interrupt_cleared_queue', 'process_exit', 'process_error']
      .includes(envelope.payload?.reason)
    ? envelope.payload.reason
    : null;
  if (envelope?.type === 'result' || envelope?.type === 'error' || terminalStatusReason) {
    const closed = needsYouRegistry.close(
      { instanceId: agent.instanceId },
      { state: 'expired', reason: terminalStatusReason || envelope.type },
    );
    return closed.needs.map(need => ({ changed: true, revision: need.revision, need }));
  }
  if (envelope?.type !== 'approval_request' && envelope?.type !== 'user_input_request') return [];
  const payload = envelope.payload || {};
  try {
    const change = needsYouRegistry.open({
      kind: envelope.type === 'user_input_request' ? 'question' : 'approval',
      target: {
        instanceId: agent.instanceId,
        threadId: envelope.sessionId || agent.sessionId || payload.threadId,
        turnId: payload.turnId,
        itemId: payload.itemId,
        requestId: payload.approvalId,
      },
      payload,
      createdAt: envelope.ts || Date.now(),
    });
    if (change.need) envelope.payload = { ...payload, needId: change.need.needId };
    return [change];
  } catch (error) {
    if (process.env.LOG_STDERR) console.error('[needs-you:open]', error);
    return [];
  }
}

function createAgent(resumeId = null, cwd = WORK_DIR) {
  if (resumeId) {
    try {
      return threadRegistry.resolve({ threadId: resumeId });
    } catch (error) {
      if (error?.code !== 'stale_target') throw error;
    }
  }
  const instanceId = newInstanceId();
  let agent;
  agent = new SessionClass({
    instanceId,
    resumeId,
    cwd,
    codexBin,
    host: getAppServerHost(),
    idleTimeoutMs,
    onEvent: envelope => {
      syncRuntimeIdentity(agent, envelope);
      for (const needsYouChange of trackNeedsYou(agent, envelope)) {
        if (needsYouChange.changed) broadcastNeedsYouChange(needsYouChange);
      }
      if (envelope.type === 'message_receipt') {
        messageReceiptLedger.advanceRuntime({
          instanceId: agent.instanceId,
          clientRequestId: envelope.payload?.clientRequestId,
          receipt: {
            ...(envelope.payload || {}),
            instanceId: agent.instanceId,
          },
        });
      }
      if (envelope.type === 'thread_status') broadcastInstances();
      if (envelope.instanceId) {
        io.to(instanceRoom(envelope.instanceId)).emit('agent:event', envelope);
      }
      const push = pushDecision(envelope);
      if (push) pushNotify(push).catch(() => {});
    },
    onSessionId: sid => {
      threadRegistry.bind(agent, { threadId: sid });
    },
    onExit: () => {
      // Session process ended naturally; keep agent in map for reconnect
    },
    experimentalApi: P3_EXPERIMENTAL_ENABLED,
  });
  threadRegistry.register(agent, {
    instanceId,
    threadId: resumeId || undefined,
  });
  agents.set(instanceId, agent);
  broadcastInstances();
  return agent;
}

function forkedSessionId(response) {
  return response?.thread?.id ?? response?.threadId ?? null;
}

function broadcastInstances() {
  const list = [];
  for (const [id, a] of agents) {
    const sp = typeof a.statusPayload === 'function' ? a.statusPayload('instances') : {};
    list.push({ instanceId: id, sessionId: a.sessionId, cwd: a.cwd, state: sp.state || 'idle', busy: a.busy, queueLength: (a.inputQueue || []).length });
  }
  for (const socket of io.sockets.sockets.values()) {
    if (socket.deviceApproved !== true) continue;
    socket.emit('agent:event', {
      seq: 0, epoch: 'server', sessionId: null, ts: Date.now(),
      type: 'instances',
      payload: { instances: list, viewingInstanceId: socket.data.viewingInstanceId ?? null }
    });
  }
}

// ---- 契约路由辅助 ----
function on(socket, event, handler) {
  socket.on(event, async (...args) => {
    try {
      if (socket.deviceApproved === false) {
        console.warn(`[devices] 丢弃未授权设备事件: ${event}`);
        return;
      }
      await handler(...args);
    } catch (err) {
      console.error(`[handler:${event}]`, err);
      socket.emit('agent:event', {
        seq: 0, epoch: 'server', sessionId: null, ts: Date.now(),
        type: 'error', payload: { message: `服务端处理 ${event} 出错：${err.message}`, recoverable: true }
      });
    }
  });
}

function sysTo(socket, message, isError = false) {
  socket.emit('agent:event', {
    seq: 0, epoch: 'server', sessionId: null, ts: Date.now(),
    type: 'system', payload: { message, isError }
  });
}

function ackOk(ack, payload = {}) {
  if (typeof ack === 'function') ack({ ok: true, ...payload });
}

function ackError(ack, error) {
  if (typeof ack === 'function') ack({ ok: false, error: error?.message || String(error || 'unknown error') });
}

function ackFeatureDisabled(ack, feature) {
  if (typeof ack === 'function') {
    ack({
      ok: false,
      errorCode: 'feature_disabled',
      error: `${feature} controls are disabled`,
      retryable: false,
    });
  }
}

function requireP3Experimental(ack) {
  if (P3_EXPERIMENTAL_ENABLED) return true;
  ackFeatureDisabled(ack, 'P3 experimental');
  return false;
}

function ensureControlAgent(cwd = WORK_DIR, socket = null) {
  if (!socket) throw new Error('Socket context is required for control routing');
  const routedCwd = routeCwd(cwd);
  let ai = routeInstance(socket.data.viewingInstanceId) ?? routeInstance(socket.data.controlInstanceId);
  if (!ai || ai.cwd !== routedCwd) {
    ai = createAgent(null, routedCwd);
    broadcastInstances();
  }
  socket.data.controlInstanceId = ai.instanceId;
  socket.join(instanceRoom(ai.instanceId));
  return ai;
}

function normalizeThread(thread, { archived = false } = {}) {
  const secondsToMs = value => Number.isFinite(value) ? value * 1000 : null;
  const createdAt = secondsToMs(thread?.createdAt) ?? Date.now();
  const lastUsedAt = secondsToMs(thread?.recencyAt ?? thread?.updatedAt ?? thread?.createdAt) ?? createdAt;
  return {
    id: thread?.id || '',
    sessionId: thread?.sessionId || thread?.id || '',
    title: thread?.name || thread?.preview || '未命名',
    preview: thread?.preview || '',
    cwd: thread?.cwd || WORK_DIR,
    model: thread?.modelProvider || '',
    createdAt,
    lastUsedAt,
    status: thread?.status || null,
    archived,
    source: 'app-server',
  };
}



function findClientRequestInThread(thread, clientRequestId) {
  const turns = Array.isArray(thread?.turns) ? thread.turns : [];
  for (const turn of turns) {
    const items = Array.isArray(turn?.items) ? turn.items : [];
    const item = items.find(candidate => (
      candidate?.type === 'userMessage'
      && candidate.clientId === clientRequestId
    ));
    if (item) {
      return {
        turnId: typeof turn?.id === 'string' ? turn.id : null,
        itemId: typeof item?.id === 'string' ? item.id : null,
      };
    }
  }
  return null;
}

function emitServerEnvelope(socket, type, payload) {
  const agent = routeInstance(socket.data.viewingInstanceId);
  socket.emit('agent:event', {
    seq: 0,
    epoch: 'server',
    sessionId: agent?.sessionId ?? null,
    instanceId: agent?.instanceId ?? null,
    ts: Date.now(),
    type,
    payload,
  });
}

function appendAdminAudit(entry) {
  try {
    mkdirSync(DATA_DIR, { recursive: true, mode: 0o700 });
    appendOwnerOnlyFile(
      ADMIN_AUDIT_FILE,
      JSON.stringify({ ts: Date.now(), ...sanitizeAdminAuditValue(entry) }) + '\n',
    );
  } catch {
    // Admin audit failures should not leak details or crash the socket handler.
  }
}

function sanitizeAdminAuditValue(value, depth = 0) {
  if (depth > 10) return '[too deep]';
  if (typeof value === 'string') return sanitize(value);
  if (Array.isArray(value)) return value.map(v => sanitizeAdminAuditValue(v, depth + 1));
  if (value && typeof value === 'object') {
    return Object.fromEntries(Object.entries(value).map(([key, nested]) => (
      [key, sanitizeAdminAuditValue(nested, depth + 1)]
    )));
  }
  return value;
}

function adminSummary(action, payload = {}) {
  if (action === 'admin:configWrite') {
    return {
      keyPath: payload.keyPath || null,
      mergeStrategy: payload.mergeStrategy || null,
      filePath: payload.filePath ? sanitizePath(payload.filePath) : null,
    };
  }
  if (action === 'admin:configBatchWrite') {
    return {
      edits: Array.isArray(payload.edits) ? payload.edits.length : 0,
      keyPaths: Array.isArray(payload.edits) ? payload.edits.map(edit => edit?.keyPath).filter(Boolean).slice(0, 20) : [],
      filePath: payload.filePath ? sanitizePath(payload.filePath) : null,
    };
  }
  if (action === 'admin:pluginInstall') {
    return {
      pluginName: payload.pluginName || null,
      remoteMarketplaceName: payload.remoteMarketplaceName || null,
      marketplacePath: payload.marketplacePath ? sanitizePath(payload.marketplacePath) : null,
    };
  }
  if (action === 'admin:pluginUninstall') return { pluginId: payload.pluginId || null };
  if (action === 'admin:marketplaceAdd') return { source: payload.source || null, refName: payload.refName || null };
  if (action === 'admin:marketplaceRemove' || action === 'admin:marketplaceUpgrade') {
    return { marketplaceName: payload.marketplaceName || null };
  }
  if (action === 'admin:fsWriteFile') {
    return {
      path: payload.path ? sanitizePath(payload.path) : null,
      dataBase64: '<redacted>',
      approxBytes: typeof payload.dataBase64 === 'string' ? Math.floor(payload.dataBase64.length * 0.75) : 0,
    };
  }
  if (action === 'admin:fsRemove') {
    return { path: payload.path ? sanitizePath(payload.path) : null, recursive: payload.recursive, force: payload.force };
  }
  if (action === 'admin:fsCopy') {
    return {
      sourcePath: payload.sourcePath ? sanitizePath(payload.sourcePath) : null,
      destinationPath: payload.destinationPath ? sanitizePath(payload.destinationPath) : null,
      recursive: payload.recursive,
    };
  }
  if (action === 'admin:mcpToolCall') {
    return { server: payload.server || null, tool: payload.tool || null, arguments: '<redacted>' };
  }
  if (action === 'admin:accountLogout') return {};
  return {};
}

function denyAdmin(socket, ack, action, payload, error) {
  appendAdminAudit({
    event: 'denied',
    action,
    socketId: socket.id,
    error,
    summary: adminSummary(action, payload),
  });
  ackError(ack, new Error(error));
}

function requireAdmin(socket, ack, action, payload = {}) {
  if (!ADMIN_ENABLED) {
    appendAdminAudit({
      event: 'denied',
      action,
      socketId: socket.id,
      error: 'Admin controls are disabled',
      summary: adminSummary(action, payload),
    });
    ackFeatureDisabled(ack, 'Admin');
    return false;
  }
  if (
    socket.adminMode === true
    && (!Number.isFinite(socket.data.adminExpiresAt) || socket.data.adminExpiresAt <= Date.now())
  ) {
    socket.adminMode = false;
    socket.data.adminExpiresAt = null;
    appendAdminAudit({
      event: 'expired',
      action,
      socketId: socket.id,
      summary: adminSummary(action, payload),
    });
    if (typeof ack === 'function') {
      ack({
        ok: false,
        errorCode: 'admin_locked',
        error: 'Admin mode expired',
        retryable: false,
      });
    }
    return false;
  }
  if (socket.adminMode !== true) {
    denyAdmin(socket, ack, action, payload, 'Admin mode is locked');
    return false;
  }
  if (payload.adminConfirm !== action) {
    denyAdmin(socket, ack, action, payload, `Missing per-action confirm: ${action}`);
    return false;
  }
  return true;
}

async function runAdminAction(socket, ack, action, payload, operation) {
  if (!requireAdmin(socket, ack, action, payload)) return;
  try {
    const result = await operation();
    appendAdminAudit({
      event: 'success',
      action,
      socketId: socket.id,
      summary: adminSummary(action, payload),
    });
    ackOk(ack, { result: result ?? null });
  } catch (err) {
    appendAdminAudit({
      event: 'error',
      action,
      socketId: socket.id,
      error: err.message,
      summary: adminSummary(action, payload),
    });
    ackError(ack, err);
  }
}

// ---- Socket.IO 连接处理 ----
io.on('connection', socket => {
  console.log(`[conn] ${socket.id} 已连接（来自 ${clientIp(socket.handshake.address)}）`);

  if (socket.deviceApproved === false) {
    socket.emit('agent:event', {
      seq: 0, epoch: 'server', sessionId: null, ts: Date.now(),
      type: 'device_status', payload: { status: 'pending', deviceId: socket.handshake.auth?.deviceToken }
    });
  } else {
    // 已授权：发送初始状态
    socket.emit('agent:event', {
      seq: 0, epoch: 'server', sessionId: null, instanceId: null, ts: Date.now(),
      type: 'init', payload: buildInitPayload()
    });
    socket.emit('agent:event', {
      seq: 0, epoch: 'server', sessionId: null, ts: Date.now(),
      type: 'pending_devices', payload: pendingDevicesPayload()
    });
  }

  // 连接 RTT 探活：客户端定时 emit，服务端立即 ack。无业务副作用。
  // 走裸 socket.on（不经 on() 的 deviceApproved 闸）——待审批设备也能看到网络延迟。
  socket.on('conn:ping', (_payload, ack) => {
    if (typeof ack === 'function') ack({ ok: true, t: Date.now() });
  });

  on(socket, 'needs-you:snapshot', (_payload = {}, ack) => {
    ackOk(ack, needsYouRegistry.snapshot());
  });

  on(socket, 'message:reconcile', async (payload = {}, ack) => {
    const clientRequestId = typeof payload?.clientRequestId === 'string'
      ? payload.clientRequestId
      : '';
    const threadId = typeof payload?.threadId === 'string' ? payload.threadId : '';
    const deviceToken = typeof socket.handshake.auth?.deviceToken === 'string'
      ? socket.handshake.auth.deviceToken.trim()
      : '';
    if (!CLIENT_REQUEST_ID_PATTERN.test(clientRequestId)) {
      if (typeof ack === 'function') {
        ack({
          ok: false,
          errorCode: 'invalid_client_request_id',
          error: 'clientRequestId 格式无效',
          retryable: false,
        });
      }
      return;
    }
    if (!deviceToken) {
      if (typeof ack === 'function') {
        ack({
          ok: false,
          errorCode: 'client_identity_required',
          error: '消息核对需要稳定的 deviceToken',
          retryable: false,
        });
      }
      return;
    }
    const replayed = await messageReceiptLedger.replayByRequest({
      identity: `device:${deviceToken}`,
      requestId: clientRequestId,
    });
    if (replayed) {
      ackOk(ack, {
        resolved: true,
        source: 'receipt_ledger',
        gatewayEpoch: GATEWAY_EPOCH,
        ...(replayed.receipt ? { receipt: replayed.receipt } : { outcome: replayed }),
      });
      return;
    }
    if (!threadId) {
      ackOk(ack, {
        resolved: false,
        source: 'thread/read',
        gatewayEpoch: GATEWAY_EPOCH,
        resultUnknown: true,
        errorCode: 'thread_required',
      });
      return;
    }
    try {
      const thread = await ensureControlAgent(payload?.cwd, socket).readThread({
        threadId,
        includeTurns: true,
      });
      const match = findClientRequestInThread(thread, clientRequestId);
      if (!match) {
        ackOk(ack, {
          resolved: false,
          source: 'thread/read',
          gatewayEpoch: GATEWAY_EPOCH,
          resultUnknown: true,
          errorCode: 'client_request_not_found',
        });
        return;
      }
      const receipt = {
        clientRequestId,
        threadId,
        ...(match.turnId ? { turnId: match.turnId } : {}),
        ...(match.itemId ? { itemId: match.itemId } : {}),
        state: 'submitted',
      };
      ackOk(ack, {
        resolved: true,
        source: 'thread/read',
        gatewayEpoch: GATEWAY_EPOCH,
        receipt,
      });
    } catch (error) {
      if (typeof ack === 'function') {
        ack({
          ok: false,
          errorCode: 'reconcile_failed',
          error: error?.message || '消息核对失败',
          retryable: true,
          resultUnknown: true,
          gatewayEpoch: GATEWAY_EPOCH,
        });
      }
    }
  });

  on(socket, 'user:message', async (payload, ack) => {
    const text = typeof payload === 'string'
      ? payload
      : (typeof payload?.text === 'string' ? payload.text : '');
    const attachments = payload?.attachments;
    const requestedParts = payload?.parts;
    const suppliedClientRequestId = payload?.clientRequestId;
    const clientRequestId = typeof suppliedClientRequestId === 'string'
      ? suppliedClientRequestId
      : '';

    if (
      (!text || !text.trim())
      && (!attachments || attachments.length === 0)
      && (!requestedParts || requestedParts.length === 0)
    ) {
      sysTo(socket, '消息为空或格式无效', true);
      if (typeof ack === 'function') {
        ack({
          ok: false,
          errorCode: 'invalid_message',
          error: '消息为空或格式无效',
          retryable: false,
        });
      }
      return;
    }

    // 校验附件
    const attachErr = validateAttachments(attachments);
    if (attachErr) {
      sysTo(socket, attachErr, true);
      if (typeof ack === 'function') {
        ack({
          ok: false,
          errorCode: 'invalid_attachments',
          error: attachErr,
          retryable: false,
        });
      }
      return;
    }

    if (text && text.length > 50000) {
      const error = `消息过长（${text.length} 字符，上限 50000），未发送`;
      sysTo(socket, error, true);
      if (typeof ack === 'function') {
        ack({
          ok: false,
          errorCode: 'message_too_long',
          error,
          retryable: false,
        });
      }
      return;
    }
    if (
      requestedParts !== undefined
      && (!Array.isArray(requestedParts) || requestedParts.length === 0 || requestedParts.length > 20)
    ) {
      if (typeof ack === 'function') {
        ack({
          ok: false,
          errorCode: 'invalid_input_parts',
          error: '结构化输入格式无效',
          retryable: false,
        });
      }
      return;
    }
    if (
      suppliedClientRequestId !== undefined
      && !CLIENT_REQUEST_ID_PATTERN.test(clientRequestId)
    ) {
      if (typeof ack === 'function') {
        ack({
          ok: false,
          errorCode: 'invalid_client_request_id',
          error: 'clientRequestId 格式无效',
          retryable: false,
        });
      }
      return;
    }
    const explicitInstanceId = typeof payload?.instanceId === 'string' ? payload.instanceId : null;
    const requestedThreadId = typeof payload?.threadId === 'string' ? payload.threadId : null;
    const deviceToken = typeof socket.handshake.auth?.deviceToken === 'string'
      ? socket.handshake.auth.deviceToken.trim()
      : '';
    if (clientRequestId && !deviceToken) {
      if (typeof ack === 'function') {
        ack({
          ok: false,
          errorCode: 'client_identity_required',
          error: 'clientRequestId 需要稳定的 deviceToken',
          retryable: false,
        });
      }
      return;
    }
    const clientIdentity = deviceToken ? `device:${deviceToken}` : `socket:${socket.id}`;
    const attachmentFingerprints = clientRequestId
      ? await canonicalAttachmentFingerprints(attachments)
      : [];
    const turnOverrides = sanitizeTurnOverrides(payload?.turn);
    const requestFingerprint = clientRequestId
      ? createHash('sha256').update(JSON.stringify({
        text: text.trim(),
        attachments: attachmentFingerprints,
        parts: canonicalInputPartFingerprints(requestedParts),
        turn: Object.keys(turnOverrides).length ? turnOverrides : null,
        target: requestedThreadId
          ? { threadId: requestedThreadId }
          : { instanceId: explicitInstanceId, newThread: !explicitInstanceId },
      })).digest('hex')
      : null;
    const receiptClaim = clientRequestId
      ? messageReceiptLedger.claim({
        identity: clientIdentity,
        requestId: clientRequestId,
        fingerprint: requestFingerprint,
      })
      : null;
    if (receiptClaim?.kind === 'conflict') {
      if (typeof ack === 'function') {
        ack({
          ok: false,
          errorCode: 'request_id_conflict',
          error: 'clientRequestId 已用于不同的消息或目标',
        });
      }
      return;
    }
    if (receiptClaim?.kind === 'full') {
      if (typeof ack === 'function') {
        ack({
          ok: false,
          errorCode: 'receipt_ledger_full',
          error: '消息回执账本已满，请稍后重试',
          retryable: true,
        });
      }
      return;
    }
    if (receiptClaim?.kind === 'duplicate') {
      const previousResult = await messageReceiptLedger.replay(receiptClaim.handle);
      if (typeof ack === 'function') ack({ ...previousResult, duplicate: true });
      return;
    }

    const dispatch = (async () => {
      const targetInstanceId = explicitInstanceId || socket.data.viewingInstanceId;
      let ai = null;
      if (targetInstanceId || requestedThreadId) {
        try {
          ai = resolveRuntimeTarget({
            instanceId: targetInstanceId,
            threadId: requestedThreadId,
          });
        } catch {
          return {
            ok: false,
            errorCode: 'stale_target',
            error: '消息目标已失效，请重新选择会话',
          };
        }
      }
      if (explicitInstanceId && !ai) {
        return {
          ok: false,
          errorCode: 'stale_target',
          error: '消息目标已失效，请重新选择会话',
        };
      }
      if (!ai) {
        // 无显式目标时只新建临时实例；浏览器负责恢复自己的按 cwd thread 指针。
        ai = createAgent(null, WORK_DIR);
        setSocketViewingInstance(socket, ai.instanceId);
      }
      if (
        receiptClaim?.kind === 'owner'
        && !messageReceiptLedger.bindRuntime(receiptClaim.handle, {
          instanceId: ai.instanceId,
          clientRequestId,
        })
      ) {
        return {
          ok: false,
          errorCode: 'request_id_conflict',
          error: 'clientRequestId 已绑定到不同的运行实例',
        };
      }
      // 先解析目标 Runtime，再在它的 cwd 内落盘；ledger 已占位可避免并发重试重复写文件。
      let savedAttachments;
      if (attachments?.length) {
        try {
          savedAttachments = await saveAttachments(ai.cwd || WORK_DIR, attachments);
        } catch (err) {
          const error = `附件保存失败：${err.message}`;
          sysTo(socket, error, true);
          return { ok: false, errorCode: 'attachment_save_failed', error };
        }
      }
      let resolvedParts;
      if (requestedParts?.length) {
        try {
          let skillEntries = [];
          if (requestedParts.some(part => part?.kind === 'skill')) {
            const response = await ai.listSkills({ forceReload: false });
            skillEntries = response?.data || [];
          }
          resolvedParts = await resolveInputParts(requestedParts, {
            cwd: ai.cwd || WORK_DIR,
            skillEntries,
            allowRemoteImages: REMOTE_IMAGE_INPUTS_ENABLED,
          });
        } catch (err) {
          return {
            ok: false,
            errorCode: 'invalid_input_parts',
            error: err?.message || '结构化输入格式无效',
            retryable: false,
          };
        }
      }
      const fallbackReceiptState = ai.busy
        ? (ai.currentTurnId ? 'steered' : 'queued')
        : 'submitted';
      let outcome;
      if (clientRequestId && typeof ai.dispatchUserMessage === 'function') {
        outcome = await ai.dispatchUserMessage({
          text: text.trim(),
          savedAttachments,
          parts: resolvedParts,
          clientRequestId,
          turn: turnOverrides,
        });
      } else {
        if (typeof ai.applyTurnOverrides === 'function') ai.applyTurnOverrides(turnOverrides);
        outcome = {
          accepted: await ai.send(text.trim(), savedAttachments, resolvedParts),
          state: fallbackReceiptState,
          threadId: ai.sessionId ?? requestedThreadId,
        };
      }
      const result = {
        ok: outcome.accepted !== false,
        instanceId: ai.instanceId,
        threadId: outcome.threadId ?? ai.sessionId ?? requestedThreadId,
      };
      if (!result.ok) {
        result.errorCode = outcome.reason || 'dispatch_rejected';
        result.error = '消息未被 Codex runtime 接受';
        result.retryable = outcome.reason === 'queue_full';
      }
      if (clientRequestId && result.ok) {
        result.receipt = {
          clientRequestId,
          instanceId: ai.instanceId,
          threadId: result.threadId,
          state: outcome.state,
        };
        if (outcome.turnId) result.receipt.turnId = outcome.turnId;
        if (outcome.position) result.receipt.position = outcome.position;
        if (outcome.queuedAt) result.receipt.queuedAt = outcome.queuedAt;
      }
      return result;
    })();
    let result;
    try {
      result = await dispatch;
    } catch (error) {
      result = {
        ok: false,
        errorCode: 'dispatch_failed',
        error: error?.message || '消息派发失败',
        retryable: true,
        resultUnknown: true,
      };
    }
    if (receiptClaim?.kind === 'owner') {
      messageReceiptLedger.settle(receiptClaim.handle, result);
    }
    if (typeof ack === 'function') {
      ack({ ...result, duplicate: false });
    }
  });

  on(socket, 'user:interrupt', async (payload = {}, ack) => {
    const instanceId = typeof payload?.instanceId === 'string'
      ? payload.instanceId
      : socket.data.viewingInstanceId;
    const threadId = typeof payload?.threadId === 'string' ? payload.threadId : null;
    const turnId = typeof payload?.turnId === 'string' ? payload.turnId : null;
    let ai = null;
    try {
      if (instanceId || threadId || turnId) {
        ai = resolveRuntimeTarget({ instanceId, threadId, turnId });
      }
    } catch {
      if (typeof ack === 'function') {
        ack({ ok: false, errorCode: 'stale_target', error: '中断目标已失效' });
      }
      return;
    }
    if (ai?.busy) await ai.abort();
    if (typeof ack === 'function') {
      ack({ ok: true, instanceId: ai?.instanceId ?? null, threadId: ai?.sessionId ?? threadId });
    }
  });

  // 手机端审批回传（仅 app-server 后端有 respondApproval）。
  on(socket, 'user:approval', async (payload = {}, ack) => {
    const { approvalId, decision } = payload || {};
    const instanceId = typeof payload?.instanceId === 'string'
      ? payload.instanceId
      : socket.data.viewingInstanceId;
    const threadId = typeof payload?.threadId === 'string' ? payload.threadId : null;
    const turnId = typeof payload?.turnId === 'string' ? payload.turnId : null;
    const query = {
      needId: payload?.needId,
      instanceId,
      threadId,
      turnId,
      itemId: typeof payload?.itemId === 'string' ? payload.itemId : null,
      requestId: approvalId,
    };
    const outcome = await needsYouRegistry.resolve(
      query,
      { decision, answers: payload?.answers || null },
      need => {
        let ai;
        try {
          ai = resolveRuntimeTarget(need.target);
        } catch {
          return false;
        }
        const accepted = typeof ai?.respondApproval === 'function'
          ? ai.respondApproval(need.target.requestId, decision, payload)
          : false;
        if (accepted) threadRegistry.releaseRequest(ai, need.target.requestId);
        return accepted;
      },
    );
    if (outcome.changed && outcome.need) broadcastNeedsYouChange(outcome);
    const target = outcome.need?.target || query;
    const ok = outcome.kind === 'resolved' || outcome.kind === 'duplicate';
    const errorCode = outcome.kind === 'conflict'
      ? 'already_resolved'
      : outcome.kind === 'in_progress'
        ? 'resolution_in_progress'
        : outcome.kind === 'unknown'
          ? 'result_unknown'
          : ok
            ? undefined
            : 'stale_target';
    appendSecurityAudit({
      event: 'need_resolution',
      outcome: outcome.kind,
      source: 'socket',
      needKind: outcome.need?.kind ?? null,
      needRef: securityRef(outcome.need?.needId ?? payload?.needId),
      actorRef: securityRef(socket.handshake.auth?.deviceToken),
      reasonCode: errorCode ?? null,
    });
    if (typeof ack === 'function') {
      ack({
        ok,
        duplicate: outcome.kind === 'duplicate',
        errorCode,
        error: ok ? undefined : (errorCode === 'already_resolved' ? '审批已用其他结果决议' : '审批目标已失效'),
        resultUnknown: outcome.kind === 'unknown' || outcome.kind === 'in_progress',
        needId: outcome.need?.needId ?? payload?.needId ?? null,
        state: outcome.need?.state ?? null,
        revision: outcome.revision,
        instanceId: target.instanceId ?? null,
        threadId: target.threadId ?? threadId,
      });
    }
  });

  on(socket, 'account:loginStart', async (payload, ack) => {
    if (payload?.type && payload.type !== 'chatgptDeviceCode') {
      if (typeof ack === 'function') ack({ ok: false, error: '仅支持 chatgptDeviceCode 登录' });
      return;
    }
    const ai = ensureControlAgent(payload?.cwd, socket);
    if (typeof ai.startChatgptDeviceLogin !== 'function') {
      if (typeof ack === 'function') ack({ ok: false, error: '当前后端不支持 ChatGPT device code 登录' });
      return;
    }
    try {
      const response = await ai.startChatgptDeviceLogin();
      if (response?.type !== 'chatgptDeviceCode') throw new Error('account/login/start 未返回 device code');
      if (typeof ack === 'function') {
        ack({
          ok: true,
          loginId: response.loginId,
          verificationUrl: response.verificationUrl,
          userCode: response.userCode
        });
      }
    } catch (err) {
      const message = `登录启动失败：${err.message}`;
      if (typeof ack === 'function') ack({ ok: false, error: message });
      socket.emit('agent:event', {
        seq: 0, epoch: 'server', sessionId: ai.sessionId ?? null, ts: Date.now(),
        type: 'account_login', payload: { status: 'failed', error: message }
      });
    }
  });

  on(socket, 'account:loginCancel', async (payload, ack) => {
    const loginId = payload?.loginId;
    const ai = routeInstance(socket.data.controlInstanceId)
      ?? routeInstance(socket.data.viewingInstanceId);
    if (!ai || typeof ai.cancelLogin !== 'function' || typeof loginId !== 'string' || !loginId) {
      if (typeof ack === 'function') ack({ ok: false, error: '无效登录任务' });
      return;
    }
    try {
      const response = await ai.cancelLogin(loginId);
      if (typeof ack === 'function') ack({ ok: true, status: response?.status || null });
    } catch (err) {
      const message = `登录取消失败：${err.message}`;
      if (typeof ack === 'function') ack({ ok: false, error: message });
      socket.emit('agent:event', {
        seq: 0, epoch: 'server', sessionId: ai.sessionId ?? null, ts: Date.now(),
        type: 'account_login', payload: { status: 'failed', loginId, error: message }
      });
    }
  });

  on(socket, 'thread:list', async (payload = {}, ack) => {
    try {
      const cwd = routeCwd(payload?.cwd);
      const ai = ensureControlAgent(cwd, socket);
      const response = await ai.listThreads({
        cwd,
        archived: payload?.archived === true,
        limit: Number.isInteger(payload?.limit) ? payload.limit : 50,
        cursor: payload?.cursor,
        searchTerm: typeof payload?.searchTerm === 'string' ? payload.searchTerm : undefined,
      });
      ackOk(ack, {
        threads: (response?.data || []).map(thread => {
          const normalized = normalizeThread(thread, { archived: payload?.archived === true });
          const latestStatus = appServerHost?.latestThreadStatus(normalized.id);
          return latestStatus
            ? { ...normalized, status: latestStatus.status, statusRevision: latestStatus.revision }
            : normalized;
        }),
        nextCursor: response?.nextCursor ?? null,
        backwardsCursor: response?.backwardsCursor ?? null,
        archived: payload?.archived === true,
      });
    } catch (err) {
      ackError(ack, err);
    }
  });

  on(socket, 'thread:select', async (payload = {}, ack) => {
    try {
      const threadId = payload?.threadId || payload?.sessionId;
      if (typeof threadId !== 'string' || !threadId) throw new Error('无效 threadId');
      const cwd = routeCwd(payload?.cwd);
      const agent = createAgent(threadId, cwd);
      setSocketViewingInstance(socket, agent.instanceId);
      broadcastInstances();
      ackOk(ack, { sessionId: threadId, threadId, instanceId: agent.instanceId, cwd });
      socket.emit('agent:event', {
        seq: 0, epoch: 'server', sessionId: threadId, instanceId: agent.instanceId, ts: Date.now(),
        type: 'init', payload: buildInitPayload({ sessionId: threadId, instanceId: agent.instanceId, cwd })
      });
      sendActiveStatus(socket, 'thread_select');
    } catch (err) {
      ackError(ack, err);
    }
  });

  on(socket, 'thread:history', async (payload = {}, ack) => {
    try {
      const threadId = payload?.threadId || payload?.sessionId;
      if (typeof threadId !== 'string' || !threadId) throw new Error('无效 threadId');
      const thread = await ensureControlAgent(payload?.cwd, socket).readThread({
        threadId,
        includeTurns: true,
      });
      ackOk(ack, {
        thread,
        messages: normalizeThreadHistoryMessages(thread),
        source: 'thread/read',
      });
    } catch (err) {
      ackError(ack, err);
    }
  });

  on(socket, 'thread:archive', async (payload = {}, ack) => {
    try {
      await ensureControlAgent(payload?.cwd, socket).archiveThread(payload?.threadId);
      ackOk(ack, { threadId: payload?.threadId });
    } catch (err) {
      ackError(ack, err);
    }
  });

  on(socket, 'thread:unarchive', async (payload = {}, ack) => {
    try {
      await ensureControlAgent(payload?.cwd, socket).unarchiveThread(payload?.threadId);
      ackOk(ack, { threadId: payload?.threadId });
    } catch (err) {
      ackError(ack, err);
    }
  });

  on(socket, 'thread:delete', async (payload = {}, ack) => {
    try {
      const threadId = payload?.threadId;
      await ensureControlAgent(payload?.cwd, socket).deleteThread(threadId);
      for (const [instanceId, agent] of agents) {
        if (agent.sessionId === threadId) {
          agent.dispose();
          threadRegistry.release(agent);
          agents.delete(instanceId);
          clearSocketInstanceReferences(instanceId);
        }
      }
      broadcastInstances();
      ackOk(ack, { threadId });
    } catch (err) {
      ackError(ack, err);
    }
  });

  on(socket, 'thread:rename', async (payload = {}, ack) => {
    try {
      await ensureControlAgent(payload?.cwd, socket).renameThread(payload?.threadId, payload?.name);
      ackOk(ack, { threadId: payload?.threadId, name: String(payload?.name || '').trim() });
    } catch (err) {
      ackError(ack, err);
    }
  });

  on(socket, 'thread:compact', async (payload = {}, ack) => {
    try {
      await ensureControlAgent(payload?.cwd, socket).compactThread(payload?.threadId);
      ackOk(ack, { threadId: payload?.threadId });
    } catch (err) {
      ackError(ack, err);
    }
  });

  on(socket, 'thread:rollback', async (payload = {}, ack) => {
    try {
      const response = await ensureControlAgent(payload?.cwd, socket).rollbackThread({
        threadId: payload?.threadId,
        numTurns: payload?.numTurns,
      });
      emitServerEnvelope(socket, 'rollback', { threadId: payload?.threadId, numTurns: payload?.numTurns || 1 });
      ackOk(ack, { thread: response?.thread || null });
    } catch (err) {
      ackError(ack, err);
    }
  });

  on(socket, 'models:read', async (payload = {}, ack) => {
    try {
      const ai = ensureControlAgent(payload?.cwd, socket);
      const [models, capabilities] = await Promise.all([
        ai.listModels({ includeHidden: payload?.includeHidden === true }),
        ai.readModelProviderCapabilities(),
      ]);
      ackOk(ack, { models: models?.data || [], nextCursor: models?.nextCursor ?? null, capabilities });
    } catch (err) {
      ackError(ack, err);
    }
  });

  on(socket, 'fs:readDirectory', async (payload = {}, ack) => {
    try {
      const response = await ensureControlAgent(payload?.cwd, socket).readDirectory(payload?.path || WORK_DIR);
      ackOk(ack, { entries: response?.entries || [], path: payload?.path || WORK_DIR });
    } catch (err) {
      ackError(ack, err);
    }
  });

  on(socket, 'fs:readFile', async (payload = {}, ack) => {
    try {
      const response = await ensureControlAgent(payload?.cwd, socket).readFile(payload?.path);
      ackOk(ack, { dataBase64: response?.dataBase64 || '', path: payload?.path });
    } catch (err) {
      ackError(ack, err);
    }
  });

  on(socket, 'files:search', async (payload = {}, ack) => {
    try {
      const cwd = routeCwd(payload?.cwd);
      const query = typeof payload?.query === 'string' ? payload.query : '';
      const paths = await searchFiles(cwd, query);
      ackOk(ack, { paths, cwd });
    } catch (err) {
      ackError(ack, err);
    }
  });

  on(socket, 'git:status', async (payload = {}, ack) => {
    try {
      const cwd = routeCwd(payload?.cwd);
      const result = await listGitChanges(cwd);
      if (!result.ok) {
        if (typeof ack === 'function') ack({ ok: false, error: result.error, errorCode: result.code });
        return;
      }
      ackOk(ack, result);
    } catch (err) {
      ackError(ack, err);
    }
  });

  on(socket, 'git:diff', async (payload = {}, ack) => {
    try {
      const cwd = routeCwd(payload?.cwd);
      const side = payload?.side === 'staged' ? 'staged' : 'unstaged';
      const result = await readGitDiff(cwd, payload?.path, side);
      if (!result.ok) {
        if (typeof ack === 'function') ack({ ok: false, error: result.error, errorCode: result.code });
        return;
      }
      ackOk(ack, result);
    } catch (err) {
      ackError(ack, err);
    }
  });

  on(socket, 'account:read', async (payload = {}, ack) => {
    try {
      const ai = ensureControlAgent(payload?.cwd, socket);
      const [account, usage, rateLimits] = await Promise.all([
        ai.readAccount(),
        ai.readUsage(),
        ai.readRateLimits(),
      ]);
      ackOk(ack, { account, usage, rateLimits });
    } catch (err) {
      ackError(ack, err);
    }
  });

  on(socket, 'mcp:read', async (payload = {}, ack) => {
    try {
      const response = await ensureControlAgent(payload?.cwd, socket).listMcpServerStatus({ limit: payload?.limit || 50 });
      ackOk(ack, { servers: response?.data || [], nextCursor: response?.nextCursor ?? null });
    } catch (err) {
      ackError(ack, err);
    }
  });

  on(socket, 'skills:read', async (payload = {}, ack) => {
    try {
      const response = await ensureControlAgent(payload?.cwd, socket).listSkills({ forceReload: payload?.forceReload === true });
      ackOk(ack, { entries: response?.data || [] });
    } catch (err) {
      ackError(ack, err);
    }
  });

  on(socket, 'externalAgentConfig:detect', async (payload = {}, ack) => {
    try {
      const response = await ensureControlAgent(payload?.cwd, socket).detectExternalAgentConfig({
        includeHome: payload?.includeHome === true,
      });
      ackOk(ack, { items: response?.items || [] });
    } catch (err) {
      ackError(ack, err);
    }
  });

  on(socket, 'externalAgentConfig:import', async (payload = {}, ack) => {
    try {
      const items = Array.isArray(payload?.migrationItems) ? payload.migrationItems : [];
      if (!items.length) throw new Error('没有可导入的配置项');
      const response = await ensureControlAgent(payload?.cwd, socket).importExternalAgentConfig(items, { source: 'mobile' });
      ackOk(ack, { importId: response?.importId || null });
    } catch (err) {
      ackError(ack, err);
    }
  });

  on(socket, 'p3:capabilities', async (payload = {}, ack) => {
    if (!requireP3Experimental(ack)) return;
    try {
      const response = await ensureControlAgent(payload?.cwd, socket).listP3Capabilities();
      ackOk(ack, { capabilities: response?.data || response?.features || response || {} });
    } catch (err) {
      ackError(ack, err);
    }
  });

  on(socket, 'p3:terminalSpawn', async (payload = {}, ack) => {
    if (!requireP3Experimental(ack)) return;
    try {
      const processId = typeof payload?.processId === 'string' && payload.processId
        ? payload.processId
        : `term_${Date.now()}_${Math.random().toString(36).slice(2, 8)}`;
      const response = await ensureControlAgent(payload?.cwd, socket).spawnTerminal({
        processId,
        command: Array.isArray(payload?.command) ? payload.command : [],
        cwd: payload?.cwd ? routeCwd(payload.cwd) : WORK_DIR,
        size: {
          cols: Number.isInteger(payload?.cols) ? payload.cols : 80,
          rows: Number.isInteger(payload?.rows) ? payload.rows : 24,
        },
      });
      ackOk(ack, { processId, result: response ?? null });
    } catch (err) {
      ackError(ack, err);
    }
  });

  on(socket, 'p3:terminalWrite', async (payload = {}, ack) => {
    if (!requireP3Experimental(ack)) return;
    try {
      await ensureControlAgent(payload?.cwd, socket).writeTerminal(payload?.processId, payload?.text ?? '', {
        closeStdin: payload?.closeStdin === true,
      });
      ackOk(ack, { processId: payload?.processId });
    } catch (err) {
      ackError(ack, err);
    }
  });

  on(socket, 'p3:terminalResize', async (payload = {}, ack) => {
    if (!requireP3Experimental(ack)) return;
    try {
      await ensureControlAgent(payload?.cwd, socket).resizeTerminal(payload?.processId, {
        cols: payload?.cols,
        rows: payload?.rows,
      });
      ackOk(ack, { processId: payload?.processId });
    } catch (err) {
      ackError(ack, err);
    }
  });

  on(socket, 'p3:terminalTerminate', async (payload = {}, ack) => {
    if (!requireP3Experimental(ack)) return;
    try {
      await ensureControlAgent(payload?.cwd, socket).terminateTerminal(payload?.processId);
      ackOk(ack, { processId: payload?.processId });
    } catch (err) {
      ackError(ack, err);
    }
  });

  on(socket, 'p3:threadTurns', async (payload = {}, ack) => {
    if (!requireP3Experimental(ack)) return;
    try {
      const response = await ensureControlAgent(payload?.cwd, socket).listThreadTurns({ threadId: payload?.threadId });
      ackOk(ack, response);
    } catch (err) {
      ackError(ack, err);
    }
  });

  on(socket, 'p3:threadSearch', async (payload = {}, ack) => {
    if (!requireP3Experimental(ack)) return;
    try {
      const response = await ensureControlAgent(payload?.cwd, socket).searchThreads({
        query: payload?.query,
        limit: Number.isInteger(payload?.limit) ? payload.limit : 20,
        cursor: payload?.cursor,
        archived: payload?.archived === true,
      });
      ackOk(ack, response);
    } catch (err) {
      ackError(ack, err);
    }
  });

  on(socket, 'admin:unlock', async (payload = {}, ack) => {
    if (!ADMIN_ENABLED) {
      requireAdmin(socket, ack, 'admin:unlock', payload);
      return;
    }
    const rateLimit = adminUnlockRateLimit(socket);
    if (rateLimit) {
      appendAdminAudit({
        event: 'denied',
        action: 'admin:unlock',
        socketId: socket.id,
        error: 'Admin unlock rate limited',
        summary: {},
      });
      if (typeof ack === 'function') {
        ack({
          ok: false,
          errorCode: 'rate_limited',
          error: 'Admin unlock rate limited',
          retryable: true,
          retryAfterMs: rateLimit.retryAfterMs,
        });
      }
      return;
    }
    if (payload?.confirmText !== ADMIN_UNLOCK_PHRASE) {
      recordAdminUnlockFailure(socket);
      denyAdmin(socket, ack, 'admin:unlock', payload, 'Invalid admin unlock phrase');
      return;
    }
    adminUnlockFailureWindows.delete(adminUnlockFailureKey(socket));
    socket.adminMode = true;
    socket.data.adminExpiresAt = Date.now() + ADMIN_UNLOCK_TTL_MS;
    appendAdminAudit({ event: 'unlock', action: 'admin:unlock', socketId: socket.id, summary: {} });
    ackOk(ack, { adminMode: true, expiresAt: socket.data.adminExpiresAt });
  });

  on(socket, 'admin:lock', async (_payload = {}, ack) => {
    if (!ADMIN_ENABLED) {
      requireAdmin(socket, ack, 'admin:lock');
      return;
    }
    socket.adminMode = false;
    socket.data.adminExpiresAt = null;
    appendAdminAudit({ event: 'lock', action: 'admin:lock', socketId: socket.id, summary: {} });
    ackOk(ack, { adminMode: false });
  });

  on(socket, 'admin:configWrite', async (payload = {}, ack) => {
    await runAdminAction(socket, ack, 'admin:configWrite', payload, () =>
      ensureControlAgent(payload?.cwd, socket).writeConfigValue(payload));
  });

  on(socket, 'admin:configBatchWrite', async (payload = {}, ack) => {
    await runAdminAction(socket, ack, 'admin:configBatchWrite', payload, () =>
      ensureControlAgent(payload?.cwd, socket).writeConfigBatch(payload));
  });

  on(socket, 'admin:pluginInstall', async (payload = {}, ack) => {
    await runAdminAction(socket, ack, 'admin:pluginInstall', payload, () =>
      ensureControlAgent(payload?.cwd, socket).installPlugin(payload));
  });

  on(socket, 'admin:pluginUninstall', async (payload = {}, ack) => {
    await runAdminAction(socket, ack, 'admin:pluginUninstall', payload, () =>
      ensureControlAgent(payload?.cwd, socket).uninstallPlugin(payload?.pluginId));
  });

  on(socket, 'admin:marketplaceAdd', async (payload = {}, ack) => {
    await runAdminAction(socket, ack, 'admin:marketplaceAdd', payload, () =>
      ensureControlAgent(payload?.cwd, socket).marketplaceAdd(payload));
  });

  on(socket, 'admin:marketplaceRemove', async (payload = {}, ack) => {
    await runAdminAction(socket, ack, 'admin:marketplaceRemove', payload, () =>
      ensureControlAgent(payload?.cwd, socket).marketplaceRemove(payload?.marketplaceName));
  });

  on(socket, 'admin:marketplaceUpgrade', async (payload = {}, ack) => {
    await runAdminAction(socket, ack, 'admin:marketplaceUpgrade', payload, () =>
      ensureControlAgent(payload?.cwd, socket).marketplaceUpgrade(payload?.marketplaceName ?? null));
  });

  on(socket, 'admin:fsWriteFile', async (payload = {}, ack) => {
    await runAdminAction(socket, ack, 'admin:fsWriteFile', payload, () =>
      ensureControlAgent(payload?.cwd, socket).writeFile(payload?.path, payload?.dataBase64));
  });

  on(socket, 'admin:fsRemove', async (payload = {}, ack) => {
    await runAdminAction(socket, ack, 'admin:fsRemove', payload, () =>
      ensureControlAgent(payload?.cwd, socket).removePath(payload?.path, { recursive: payload?.recursive, force: payload?.force }));
  });

  on(socket, 'admin:fsCopy', async (payload = {}, ack) => {
    await runAdminAction(socket, ack, 'admin:fsCopy', payload, () =>
      ensureControlAgent(payload?.cwd, socket).copyPath({
        sourcePath: payload?.sourcePath,
        destinationPath: payload?.destinationPath,
        recursive: payload?.recursive,
      }));
  });

  on(socket, 'admin:mcpToolCall', async (payload = {}, ack) => {
    await runAdminAction(socket, ack, 'admin:mcpToolCall', payload, () =>
      ensureControlAgent(payload?.cwd, socket).callMcpTool({
        threadId: payload?.threadId,
        server: payload?.server,
        tool: payload?.tool,
        arguments: payload?.arguments,
        _meta: payload?._meta,
      }));
  });

  on(socket, 'admin:accountLogout', async (payload = {}, ack) => {
    await runAdminAction(socket, ack, 'admin:accountLogout', payload, () =>
      ensureControlAgent(payload?.cwd, socket).logoutAccount());
  });

  on(socket, 'session:new', (payload, maybeAck) => {
    const ack = typeof payload === 'function' ? payload : maybeAck;
    const cwd = routeCwd(payload?.cwd);
    const agent = createAgent(null, cwd);
    setSocketViewingInstance(socket, agent.instanceId);
    if (typeof ack === 'function') {
      ack({ ok: true, instanceId: agent.instanceId, threadId: null, cwd });
    }
    socket.emit('agent:event', {
      seq: 0, epoch: 'server', sessionId: null, instanceId: agent.instanceId, ts: Date.now(),
      type: 'init', payload: buildInitPayload({ instanceId: agent.instanceId, cwd })
    });
    broadcastInstances();
  });

  on(socket, 'session:fork', async (payload, ack) => {
    const targetInstanceId = payload?.instanceId || socket.data.viewingInstanceId;
    const threadId = typeof payload?.threadId === 'string' && payload.threadId
      ? payload.threadId
      : null;
    let ai = null;
    try {
      if (targetInstanceId || threadId) {
        ai = resolveRuntimeTarget({ instanceId: targetInstanceId, threadId });
      }
    } catch {
      ai = null;
    }
    const resolvedThreadId = threadId || ai?.sessionId;
    if (!ai || !resolvedThreadId || typeof ai.forkThread !== 'function') {
      if (typeof ack === 'function') ack({ ok: false, error: '当前没有可分叉的会话' });
      else sysTo(socket, '当前没有可分叉的会话', true);
      return;
    }

    try {
      const response = await ai.forkThread({
        threadId: resolvedThreadId,
        ephemeral: payload?.ephemeral === true
      });
      const sessionId = forkedSessionId(response);
      if (!sessionId) throw new Error('thread/fork 未返回 thread.id');
      const cwd = ai.cwd || WORK_DIR;
      const agent = createAgent(sessionId, cwd);
      setSocketViewingInstance(socket, agent.instanceId);
      if (typeof ack === 'function') {
        ack({ ok: true, sessionId, threadId: sessionId, instanceId: agent.instanceId, cwd });
      }
      socket.emit('agent:event', {
        seq: 0, epoch: 'server', sessionId, instanceId: agent.instanceId, ts: Date.now(),
        type: 'init', payload: buildInitPayload({ sessionId, instanceId: agent.instanceId, cwd })
      });
      broadcastInstances();
      sendActiveStatus(socket, 'session_fork');
    } catch (err) {
      const message = `会话分叉失败：${err.message}`;
      if (typeof ack === 'function') ack({ ok: false, error: message });
      socket.emit('agent:event', {
        seq: 0, epoch: 'server', sessionId: ai.sessionId ?? null, ts: Date.now(),
        type: 'error', payload: { message, recoverable: true }
      });
    }
  });

  on(socket, 'session:switch', (payload = {}, ack) => {
    const iid = payload?.instanceId;
    let ai = null;
    try {
      ai = resolveRuntimeTarget({ instanceId: iid });
    } catch {
      ai = null;
    }
    if (ai) {
      setSocketViewingInstance(socket, iid);
      broadcastInstances();
      if (typeof ack === 'function') {
        ack({ ok: true, instanceId: iid, threadId: ai?.sessionId ?? null });
      }
      return;
    }
    if (typeof ack === 'function') {
      ack({ ok: false, errorCode: 'stale_target', error: '实例不存在或已结束' });
    }
  });

  on(socket, 'catch-up', async (payload, ack) => {
    const { sessionId, lastSeq } = payload || {};
    if (typeof ack !== 'function') return;
    const instanceId = typeof payload?.instanceId === 'string'
      ? payload.instanceId
      : socket.data.viewingInstanceId;
    let ai = null;
    try {
      ai = resolveRuntimeTarget({ instanceId, threadId: sessionId });
    } catch {
      ai = null;
    }
    if (!ai) {
      return ack({
        replayed: 0,
        gap: false,
        errorCode: 'stale_target',
        instanceId: instanceId ?? null,
        threadId: sessionId ?? null,
      });
    }
    setSocketViewingInstance(socket, ai.instanceId);
    const replay = ai.eventsSince(Number(lastSeq) || 0);
    const epochMismatch = typeof payload?.lastEpoch === 'string'
      && payload.lastEpoch.length > 0
      && payload.lastEpoch !== replay.epoch;
    if (!replay.gap && !epochMismatch) {
      for (const envelope of replay.events) socket.emit('agent:event', envelope);
      return ack({
        replayed: replay.events.length,
        gap: false,
        epoch: replay.epoch,
        instanceId: ai.instanceId,
        threadId: ai.sessionId,
      });
    }

    // Freeze the snapshot watermark before thread/read. Any runtime event observed
    // while the snapshot is being read must be replayed after the rebuild, even
    // if its content raced with the app-server snapshot.
    const snapshotThroughSeq = ai.seq;
    const snapshotEpoch = ai.epoch || replay.epoch;
    try {
      const thread = await ai.readThread({ threadId: ai.sessionId, includeTurns: true });
      ack({
        replayed: 0,
        gap: true,
        rebuilt: true,
        epochMismatch,
        epoch: snapshotEpoch,
        throughSeq: snapshotThroughSeq,
        instanceId: ai.instanceId,
        threadId: ai.sessionId,
        snapshot: {
          source: 'thread/read',
          title: thread?.name || thread?.preview || ai.sessionId,
          threadStatus: thread?.status || null,
          messages: normalizeThreadHistoryMessages(thread),
        },
      });
    } catch (err) {
      ack({
        replayed: 0,
        gap: true,
        rebuilt: false,
        epochMismatch,
        epoch: snapshotEpoch,
        throughSeq: snapshotThroughSeq,
        instanceId: ai.instanceId,
        threadId: ai.sessionId,
        recoveryError: err?.message || String(err),
      });
    }
  });

  // 已信任设备远程审批待批设备
  on(socket, 'user:approveDevice', (payload, ack) => {
    const deviceId = payload?.deviceId;
    if (typeof deviceId !== 'string' || !deviceId) {
      ackError(ack, new Error('invalid_device_id'));
      return;
    }
    if (!getPendingDevices().some(d => d.deviceToken === deviceId)) {
      ackError(ack, new Error('device_not_pending'));
      return;
    }
    const approved = approveDeviceAccess(deviceId, {
      persistTrust: true,
      source: 'socket',
      actorToken: socket.handshake.auth?.deviceToken,
    });
    if (!approved) {
      ackError(ack, new Error('device_persist_failed'));
      return;
    }
    broadcastPendingDevices();
    ackOk(ack);
  });

  on(socket, 'user:denyDevice', (payload, ack) => {
    const deviceId = payload?.deviceId;
    if (typeof deviceId !== 'string' || !deviceId) {
      ackError(ack, new Error('invalid_device_id'));
      return;
    }
    const persisted = revokeDeviceAccess(deviceId, {
      removeTrust: true,
      source: 'socket',
      actorToken: socket.handshake.auth?.deviceToken,
    });
    broadcastPendingDevices();
    if (!persisted) {
      ackError(ack, new Error('device_persist_failed'));
      return;
    }
    ackOk(ack);
  });

  socket.on('disconnect', reason => {
    console.log(`[conn] ${socket.id} 已断开（${reason}）`);
  });
});

// ---- 状态栏刷新 ----
let statusRefreshTimer = null;
let pruneUploadsTimer = null;

async function refreshStatusLine() {
  const tasks = [];
  for (const socket of io.sockets.sockets.values()) {
    if (socket.deviceApproved !== true) continue;
    tasks.push((async () => {
      try {
        const agent = agents.get(socket.data.viewingInstanceId) ?? null;
        const payload = await buildStatusLine({
          agent,
          cwd: agent?.cwd || WORK_DIR,
          versions
        });
        socket.emit('agent:event', {
          seq: 0, epoch: 'server', sessionId: agent?.sessionId ?? null, ts: Date.now(),
          type: 'status_line', payload
        });
      } catch (err) {
        console.error('[statusline] 刷新失败:', err.message);
      }
    })());
  }
  await Promise.all(tasks);
}

function scheduleStatusRefresh() {
  clearInterval(statusRefreshTimer);
  statusRefreshTimer = setInterval(refreshStatusLine, 4_000);
  refreshStatusLine(); // 立即刷新一次
}

// ---- 启动 ----
export function startServer() {
  if (workDirs.length === 0) initializeWorkDirs();
  startTrustedDevicesWatcher();
  httpServer.listen(PORT, HOST, () => {
    const displayHost = HOST === '0.0.0.0' ? 'localhost' : HOST;
    const address = httpServer.address();
    const displayPort = typeof address === 'object' && address ? address.port : PORT;
    console.log(`🚀 Codex Chat Mobile 运行在 http://${displayHost}:${displayPort}`);
    scheduleStatusRefresh();

    // 启动时清理过期附件
    for (const dir of workDirs) {
      pruneExpiredUploads(dir).catch(() => {});
    }

    // 每 1 小时自动定时清理
    pruneUploadsTimer = setInterval(() => {
      for (const dir of workDirs) {
        pruneExpiredUploads(dir).catch(() => {});
      }
    }, 3600000);
    pruneUploadsTimer.unref?.();

    // 每 5 分钟清理过期认证会话，防止内存泄漏
    authSessionsPruneTimer = setInterval(pruneExpiredAuthSessions, 300_000);
    authSessionsPruneTimer.unref?.();

    // 每 5 分钟清理过期限流窗口
    failureWindowsPruneTimer = setInterval(pruneExpiredFailureWindows, 300_000);
    failureWindowsPruneTimer.unref?.();
  });
  return httpServer;
}

export function stopServer(callback) {
  stopTrustedDevicesWatcher();
  clearInterval(statusRefreshTimer);
  statusRefreshTimer = null;
  clearInterval(pruneUploadsTimer);
  pruneUploadsTimer = null;
  clearInterval(authSessionsPruneTimer);
  authSessionsPruneTimer = null;
  clearInterval(failureWindowsPruneTimer);
  failureWindowsPruneTimer = null;
  for (const agent of agents.values()) {
    try { agent.dispose?.(); } catch { /* noop */ }
    threadRegistry.release(agent);
  }
  agents.clear();
  messageReceiptLedger.clear();
  needsYouRegistry.clear();
  authFailureWindows.clear();
  adminUnlockFailureWindows.clear();
  authSessions.clear();
  appServerHost?.dispose();
  appServerHost = null;
  if (!httpServer.listening) {
    callback?.();
    return;
  }
  httpServer.close(callback);
}

if (shouldStartServer) startServer();

// 优雅退出
function shutdown() {
  console.log('\n[server] 正在关闭...');
  process.exit(0);
}
if (shouldStartServer) {
  process.on('SIGTERM', shutdown);
  process.on('SIGINT', shutdown);
}
