// server.js —— Express 静态托管 + Socket.IO 契约层。
// 会话与 socket 解耦：CodexSession 挂在服务端，事件 io.emit 广播（多设备同看）。
// Generated by claude-sonnet-4-6
import dotenv from 'dotenv';
import { createServer } from 'node:http';
import { statSync, existsSync, mkdirSync, realpathSync, readFileSync } from 'node:fs';
import { homedir } from 'node:os';
import { join } from 'node:path';
import { execSync } from 'node:child_process';
import { timingSafeEqual } from 'node:crypto';
import { watch } from 'node:fs';
import express from 'express';
import compression from 'compression';
import { Server } from 'socket.io';
import { CodexAppServerSession } from './agent-appserver.js';
import * as sessions from './sessions.js';
import { maskToken, sanitizePath } from './sanitizer.js';
import { writeOwnerOnlyFile } from './file-security.js';
import { validateAttachments, saveAttachments, pruneExpiredUploads } from './uploads.js';
import { buildStatusLine } from './statusline.js';
import { listSessions as listCodexSessions, getSessionHistory } from './history.js';
import webpush from 'web-push';
import {
  isDeviceTrusted,
  addPendingDevice,
  getLatestPendingDevice,
  approveDevice,
  denyDevice,
  getPendingDevices
} from './devices.js';
import {
  isLocalAccess,
  isLoopbackAddress,
  isLoopbackHostHeader,
  normalizeAddress,
  resolveListenHost
} from './server-security.js';

dotenv.config();
for (const k of Object.keys(process.env)) {
  if (process.env[k] === '') delete process.env[k];
}

const {
  AUTH_TOKEN = '',
  IDLE_TIMEOUT_MS = 600000
} = process.env;

let WORK_DIR = process.env.WORK_DIR || homedir();
let workDirs = [];
const rawPort = Number(process.env.PORT);
const PORT = Number.isInteger(rawPort) && rawPort >= 0 ? rawPort : 3001;
const shouldStartServer = process.env.CODEX_SERVER_NO_START !== '1';
let HOST;
try {
  HOST = resolveListenHost({ env: process.env, authToken: AUTH_TOKEN });
} catch (err) {
  console.error(`\n❌ 启动失败：${err.message}\n`);
  process.exit(1);
}
const idleTimeoutMs = Number(IDLE_TIMEOUT_MS) > 0 ? Number(IDLE_TIMEOUT_MS) : 600000;
const HERE = import.meta.dirname;
const DATA_DIR = process.env.CODEX_DATA_DIR || join(HERE, 'data');
const ADMIN_UNLOCK_PHRASE = 'ENABLE ADMIN';
const ADMIN_AUDIT_FILE = join(DATA_DIR, 'admin-audit.jsonl');
const P3_EXPERIMENTAL_ENABLED = process.env.CODEX_P3_EXPERIMENTAL === '1';

// ---- Web Push ----
const VAPID_PUBLIC_KEY  = process.env.VAPID_PUBLIC_KEY  || '';
const VAPID_PRIVATE_KEY = process.env.VAPID_PRIVATE_KEY || '';
const VAPID_SUBJECT     = process.env.VAPID_SUBJECT     || '';
const pushEnabled = !!(VAPID_PUBLIC_KEY && VAPID_PRIVATE_KEY && VAPID_SUBJECT);
if (pushEnabled) webpush.setVapidDetails(VAPID_SUBJECT, VAPID_PUBLIC_KEY, VAPID_PRIVATE_KEY);

const PUSH_SUB_FILE = join(DATA_DIR, 'push-subscriptions.json');
let pushSubscriptions = [];
try {
  const raw = JSON.parse(readFileSync(PUSH_SUB_FILE, 'utf8'));
  pushSubscriptions = Array.isArray(raw) ? raw.filter(s => s?.endpoint) : (raw?.endpoint ? [raw] : []);
} catch {}

function persistPushSubs() {
  try { writeOwnerOnlyFile(PUSH_SUB_FILE, JSON.stringify(pushSubscriptions)); } catch {}
}

async function pushNotify(title, body) {
  if (!pushEnabled || pushSubscriptions.length === 0) return;
  const payload = JSON.stringify({ title, body });
  const expired = [];
  await Promise.all(pushSubscriptions.map(sub =>
    webpush.sendNotification(sub, payload).catch(e => {
      if (e.statusCode === 410 || e.statusCode === 404) expired.push(sub.endpoint);
    })
  ));
  if (expired.length) {
    pushSubscriptions = pushSubscriptions.filter(s => !expired.includes(s.endpoint));
    persistPushSubs();
  }
}

export function pushDecision(envelope) {
  if (!envelope || typeof envelope.type !== 'string') return null;
  if (envelope.type === 'approval_request') {
    return {
      title: 'Codex 待审批',
      body: pushText(envelope.payload?.command || envelope.payload?.reason || envelope.payload?.kind || '有操作等待审批'),
    };
  }
  if (envelope.type === 'user_input_request') {
    return {
      title: 'Codex 需要人到场',
      body: pushText(envelope.payload?.questions?.[0]?.question || '有问题等待回答'),
    };
  }
  if (envelope.type === 'approval_revoked') return null;
  if (envelope.type === 'result' || envelope.type === 'error') {
    const status = envelope.payload?.ok ? '完成' : '出错';
    return {
      title: `Codex ${status}`,
      body: pushText(envelope.payload?.status || envelope.payload?.message || '任务已完成'),
    };
  }
  return null;
}

function pushText(value) {
  const text = typeof value === 'string' ? value : String(value ?? '');
  return text.length > 180 ? `${text.slice(0, 180)} ...` : text;
}
// 仅 app-server 后端（长驻 JSON-RPC，原生流式/审批）
const SessionClass = CodexAppServerSession;

// ---- 启动预检 ----
const versions = { codex: 'unknown' };

function preflight() {
  const fail = msg => {
    console.error(`\n❌ 启动失败：${msg}\n`);
    process.exit(1);
  };
  try {
    initializeWorkDirs();
  } catch (err) {
    fail(err.message);
  }

  let codexBin = process.env.CODEX_BIN || '';
  if (!codexBin) {
    try {
      codexBin = execSync('which codex', { encoding: 'utf8' }).trim();
    } catch {
      fail('未找到 codex 命令。请先安装 Codex CLI，或在 .env 中用 CODEX_BIN 指定路径');
    }
  }
  try {
    statSync(codexBin);
  } catch {
    fail(`CODEX_BIN 指向的文件不存在：${codexBin}`);
  }
  try {
    versions.codex = execSync(`"${codexBin}" --version`, { encoding: 'utf8' }).trim();
  } catch { /* 非致命 */ }

  console.log(`\n✅ Codex Chat Mobile 启动`);
  console.log(`   WORK_DIR: ${WORK_DIR}`);
  console.log(`   CODEX_BIN: ${codexBin}`);
  console.log(`   HOST: ${HOST}`);
  console.log(`   PORT: ${PORT}`);
  console.log(`   BACKEND: app-server`);
  if (AUTH_TOKEN) console.log(`   AUTH_TOKEN: ${maskToken(AUTH_TOKEN)}`);
  else console.log(`   AUTH_TOKEN: （未设置，仅允许 loopback Host + loopback socket）`);
  console.log('');

  return codexBin;
}

function initializeWorkDirs() {
  let workDirStat;
  try {
    workDirStat = statSync(WORK_DIR);
  } catch {
    throw new Error(`WORK_DIR 不存在：${WORK_DIR}（请在 .env 中设置有效路径）`);
  }
  if (!workDirStat.isDirectory()) throw new Error(`WORK_DIR 不是目录：${WORK_DIR}`);
  WORK_DIR = realpathSync(WORK_DIR);
  workDirs = [WORK_DIR];
  const rawDirs = (process.env.WORK_DIRS || '').split(',').map(s => s.trim()).filter(Boolean);
  for (const raw of rawDirs) {
    try {
      const d = realpathSync(raw);
      if (!statSync(d).isDirectory()) { console.warn(`⚠️  WORK_DIRS 忽略（不是目录）：${raw}`); continue; }
      if (!workDirs.includes(d)) workDirs.push(d);
    } catch { console.warn(`⚠️  WORK_DIRS 忽略（不存在/不可达）：${raw}`); }
  }
}
const codexBin = shouldStartServer ? preflight() : (process.env.CODEX_BIN || 'codex');

// ---- HTTP ----
const app = express();
app.use(compression());
app.use((_req, res, next) => {
  res.setHeader('Content-Security-Policy', [
    "default-src 'self'",
    "script-src 'self' 'unsafe-inline'",
    "style-src 'self' 'unsafe-inline'",
    "img-src 'self' data:",
    "connect-src 'self' ws: wss:",
    "font-src 'self'",
    "frame-ancestors 'none'"
  ].join('; '));
  res.setHeader('X-Frame-Options', 'DENY');
  res.setHeader('X-Content-Type-Options', 'nosniff');
  res.setHeader('Referrer-Policy', 'no-referrer');
  next();
});

const clientIp = v => normalizeAddress(v);

function tokenMatches(got) {
  if (!AUTH_TOKEN || typeof got !== 'string') return false;
  const a = Buffer.from(got), b = Buffer.from(AUTH_TOKEN);
  return a.length === b.length && timingSafeEqual(a, b);
}

async function httpAuth(req, res, next) {
  if (!AUTH_TOKEN || tokenMatches(req.query.token) || tokenMatches(req.headers['x-auth-token'])) return next();
  return res.status(401).json({ status: 'unauthorized' });
}

function noTokenLocalOnly(req, res, next) {
  if (AUTH_TOKEN) return next();
  if (isLocalAccess({ remoteAddress: req.socket?.remoteAddress || req.ip, hostHeader: req.headers.host })) return next();
  return res.status(403).json({ status: 'local_access_only' });
}

app.use(noTokenLocalOnly);
app.use(express.static(join(HERE, 'public'), {
  setHeaders: (res, filePath) => {
    if (filePath.endsWith('.html')) res.setHeader('Cache-Control', 'no-store');
  }
}));

app.get('/health', httpAuth, (_req, res) => {
  res.json({
    status: 'ok',
    sessionId: routeInstance(viewingInstanceId)?.sessionId ?? null,
    busy: [...agents.values()].some(a => a.busy),
    sessionState: routeInstance(viewingInstanceId)?.statusPayload?.('health') ?? null,
    versions,
    timestamp: Date.now()
  });
});

// Push endpoints
app.get('/push/vapid-public-key', (_req, res) => {
  if (!pushEnabled) return res.status(503).json({ error: 'push not configured' });
  res.json({ key: VAPID_PUBLIC_KEY });
});
app.post('/push/subscribe', express.json({ limit: '4kb' }), (req, res) => {
  if (!pushEnabled) return res.status(503).json({ error: 'push not configured' });
  if (!req.body?.endpoint) return res.status(400).json({ error: 'invalid subscription' });
  pushSubscriptions = pushSubscriptions.filter(s => s.endpoint !== req.body.endpoint);
  pushSubscriptions.push(req.body);
  persistPushSubs();
  res.json({ ok: true });
});

const httpServer = createServer(app);
const io = new Server(httpServer, {
  perMessageDeflate: { threshold: 1024 }
});

// ---- 设备审批辅助函数 ----
function getSocketsByDeviceToken(deviceToken) {
  const list = [];
  if (!deviceToken) return list;
  for (const socket of io.sockets.sockets.values()) {
    if (socket.handshake.auth?.deviceToken === deviceToken) list.push(socket);
  }
  return list;
}

function unlockSocket(socket) {
  if (socket.deviceApproved) return;
  socket.deviceApproved = true;
  const deviceToken = socket.handshake.auth?.deviceToken;
  socket.emit('agent:event', {
    seq: 0, epoch: 'server', sessionId: null, ts: Date.now(),
    type: 'device_status', payload: { status: 'approved', deviceId: deviceToken }
  });
  const va = routeInstance(viewingInstanceId);
  if (va) {
    socket.emit('agent:event', {
      seq: 0, epoch: 'server', sessionId: null, ts: Date.now(),
      type: 'init', payload: { sessionId: va.sessionId, cwd: va.cwd, workDirs, versions }
    });
    sendActiveStatus(socket, 'device_unlocked');
  }
  sendSessionList(socket);
  broadcastPendingDevices();
  scheduleStatusRefresh();
}

function unlockDeviceSockets(deviceToken) {
  for (const socket of getSocketsByDeviceToken(deviceToken)) unlockSocket(socket);
}

function disconnectDeviceSockets(deviceToken) {
  for (const socket of getSocketsByDeviceToken(deviceToken)) {
    socket.emit('agent:event', {
      seq: 0, epoch: 'server', sessionId: null, ts: Date.now(),
      type: 'device_status', payload: { status: 'denied', deviceId: deviceToken }
    });
    socket.disconnect(true);
  }
}

function pendingDevicesPayload() {
  return { devices: getPendingDevices().map(d => ({ deviceId: d.deviceToken, ip: d.ip, userAgent: d.userAgent, ts: d.ts })) };
}

function broadcastPendingDevices() {
  const payload = pendingDevicesPayload();
  for (const socket of io.sockets.sockets.values()) {
    if (socket.deviceApproved === true) {
      socket.emit('agent:event', {
        seq: 0, epoch: 'server', sessionId: null, ts: Date.now(),
        type: 'pending_devices', payload
      });
    }
  }
}

// 初始化设备文件
const TRUSTED_DEVICES_FILE = join(DATA_DIR, 'trusted-devices.json');
const PENDING_DEVICES_FILE = join(DATA_DIR, 'pending-devices.json');
try {
  if (shouldStartServer) {
    mkdirSync(DATA_DIR, { recursive: true });
    if (!existsSync(TRUSTED_DEVICES_FILE)) writeOwnerOnlyFile(TRUSTED_DEVICES_FILE, JSON.stringify([], null, 2));
    if (!existsSync(PENDING_DEVICES_FILE)) writeOwnerOnlyFile(PENDING_DEVICES_FILE, JSON.stringify([], null, 2));
  }
} catch (err) {
  console.error('[devices] 初始化设备认证文件失败:', err.message);
}

// 监听 trusted-devices.json 变化（CLI 审批后自动解锁）
if (shouldStartServer && existsSync(TRUSTED_DEVICES_FILE)) {
  try {
    watch(TRUSTED_DEVICES_FILE, eventType => {
      if (eventType === 'change') {
        setTimeout(() => {
          for (const socket of io.sockets.sockets.values()) {
            if (socket.deviceApproved === false) {
              const token = socket.handshake.auth?.deviceToken;
              if (isDeviceTrusted(token)) {
                console.log(`[devices] 检测到变更，自动解锁设备 ${token}`);
                unlockSocket(socket);
              }
            }
          }
          broadcastPendingDevices();
        }, 100);
      }
    });
  } catch (err) {
    console.error('[devices] 无法监视 trusted-devices.json:', err.message);
  }
}

// TTY 回车一键审批
if (shouldStartServer && process.stdin.isTTY) {
  process.stdin.setEncoding('utf8');
  process.stdin.on('data', data => {
    const text = data.trim().toLowerCase();
    const latest = getLatestPendingDevice();
    if (text === '') {
      if (latest) {
        console.log(`\n[TTY] 一键批准最新设备: ${latest}`);
        approveDevice(latest);
        unlockDeviceSockets(latest);
        broadcastPendingDevices();
      }
    } else if (text === 'deny') {
      if (latest) {
        console.log(`\n[TTY] 拒绝最新设备: ${latest}`);
        denyDevice(latest);
        disconnectDeviceSockets(latest);
        broadcastPendingDevices();
      }
    }
  });
}

// ---- Socket.IO 鉴权 ----
io.use(async (socket, next) => {
  try {
    let authPassed = false;
    if (!AUTH_TOKEN) {
      authPassed = isLocalAccess({
        remoteAddress: socket.handshake.address,
        hostHeader: socket.handshake.headers.host
      });
    } else if (tokenMatches(socket.handshake.auth?.token)) {
      authPassed = true;
    }

    if (!authPassed) {
      console.warn(`[conn] ${clientIp(socket.handshake.address)} 握手鉴权失败`);
      return next(new Error('unauthorized'));
    }

    const isLocal = isLoopbackAddress(socket.handshake.address) && isLoopbackHostHeader(socket.handshake.headers.host);
    if (isLocal) {
      socket.deviceApproved = true;
    } else {
      const deviceToken = socket.handshake.auth?.deviceToken;
      if (isDeviceTrusted(deviceToken)) {
        socket.deviceApproved = true;
      } else {
        socket.deviceApproved = false;
        const ip = clientIp(socket.handshake.address);
        const ua = socket.handshake.headers['user-agent'] || 'Unknown';
        addPendingDevice(deviceToken, { ip, userAgent: ua });
        broadcastPendingDevices();

        console.log('\n==================================================');
        console.log(`📢 [安全] 发现新设备请求接入！`);
        console.log(`   设备 ID: ${deviceToken || '（未提供）'}`);
        console.log(`   来自 IP: ${ip}`);
        console.log(`   User-Agent: ${ua}`);
        if (process.stdin.isTTY) {
          console.log(`   -> 按【回车键】一键同意此设备`);
          console.log(`   -> 输入【deny】拒绝此设备`);
        } else {
          console.log(`   -> node scripts/device.js approve "${deviceToken}"`);
        }
        console.log('==================================================\n');
      }
    }

    return next();
  } catch (e) {
    return next(new Error('unauthorized'));
  }
});

// ---- 会话管理 ----
// 多实例并行：instanceId → CodexAppServerSession
const agents = new Map();
let viewingInstanceId = null;
let instanceCounter = 0;
const newInstanceId = () => `inst_${++instanceCounter}`;

// 多工作目录路由
const routeCwd = cwd => (typeof cwd === 'string' && workDirs.includes(cwd)) ? cwd : WORK_DIR;

// 实例路由
const resolveInstanceId = id => agents.has(id) ? id : viewingInstanceId;
const routeInstance = id => agents.get(resolveInstanceId(id)) ?? null;

function sendSessionList(socket, cwd) {
  const targetCwd = cwd || WORK_DIR;
  const allSessions = sessions.getState().sessions.filter(s => s.cwd === targetCwd);
  const currentId = sessions.getCurrent(targetCwd);
  socket.emit('agent:event', {
    seq: 0, epoch: 'server', sessionId: null, ts: Date.now(),
    type: 'session_list',
    payload: { sessions: allSessions, currentSessionId: currentId, cwd: targetCwd }
  });
}

function sendActiveStatus(socket, reason = 'connect') {
  const agent = routeInstance(viewingInstanceId);
  if (typeof agent?.statusPayload !== 'function') return;
  socket.emit('agent:event', {
    seq: 0,
    epoch: 'server',
    sessionId: agent.sessionId ?? null,
    ts: Date.now(),
    type: 'status',
    payload: agent.statusPayload(reason)
  });
}

function createAgent(resumeId = null, cwd = WORK_DIR) {
  const instanceId = newInstanceId();
  const agent = new SessionClass({
    instanceId,
    resumeId,
    cwd,
    codexBin,
    idleTimeoutMs,
    onEvent: envelope => {
      io.emit('agent:event', envelope);
      const push = pushDecision(envelope);
      if (push) pushNotify(push.title, push.body).catch(() => {});
    },
    onSessionId: (sid, firstMessage) => {
      sessions.upsertSession({ id: sid, title: firstMessage, cwd });
    },
    onExit: () => {
      // Session process ended naturally; keep agent in map for reconnect
    },
    experimentalApi: P3_EXPERIMENTAL_ENABLED,
  });
  agents.set(instanceId, agent);
  broadcastInstances();
  return agent;
}

function forkedSessionId(response) {
  return response?.thread?.id ?? response?.threadId ?? null;
}

function broadcastInstances() {
  const list = [];
  for (const [id, a] of agents) {
    const sp = typeof a.statusPayload === 'function' ? a.statusPayload('instances') : {};
    list.push({ instanceId: id, sessionId: a.sessionId, cwd: a.cwd, state: sp.state || 'idle', busy: a.busy, queueLength: (a.inputQueue || []).length });
  }
  io.emit('agent:event', {
    seq: 0, epoch: 'server', sessionId: null, ts: Date.now(),
    type: 'instances', payload: { instances: list, viewingInstanceId }
  });
}

function broadcastSessionList(cwd) {
  for (const socket of io.sockets.sockets.values()) {
    if (socket.deviceApproved === true) sendSessionList(socket, cwd);
  }
}

// ---- 契约路由辅助 ----
function on(socket, event, handler) {
  socket.on(event, async (...args) => {
    try {
      if (socket.deviceApproved === false) {
        console.warn(`[devices] 丢弃未授权设备事件: ${event}`);
        return;
      }
      await handler(...args);
    } catch (err) {
      console.error(`[handler:${event}]`, err);
      socket.emit('agent:event', {
        seq: 0, epoch: 'server', sessionId: null, ts: Date.now(),
        type: 'error', payload: { message: `服务端处理 ${event} 出错：${err.message}`, recoverable: true }
      });
    }
  });
}

function sysTo(socket, message, isError = false) {
  socket.emit('agent:event', {
    seq: 0, epoch: 'server', sessionId: null, ts: Date.now(),
    type: 'system', payload: { message, isError }
  });
}

function ackOk(ack, payload = {}) {
  if (typeof ack === 'function') ack({ ok: true, ...payload });
}

function ackError(ack, error) {
  if (typeof ack === 'function') ack({ ok: false, error: error?.message || String(error || 'unknown error') });
}

function requireP3Experimental(ack) {
  if (P3_EXPERIMENTAL_ENABLED) return true;
  ackError(ack, new Error('P3 experimental controls are disabled'));
  return false;
}

function ensureControlAgent(cwd = WORK_DIR) {
  const routedCwd = routeCwd(cwd);
  let ai = routeInstance(viewingInstanceId);
  if (!ai || ai.cwd !== routedCwd) {
    ai = createAgent(null, routedCwd);
    viewingInstanceId = ai.instanceId;
    broadcastInstances();
  }
  return ai;
}

function normalizeThread(thread, { archived = false } = {}) {
  const secondsToMs = value => Number.isFinite(value) ? value * 1000 : null;
  const createdAt = secondsToMs(thread?.createdAt) ?? Date.now();
  const lastUsedAt = secondsToMs(thread?.recencyAt ?? thread?.updatedAt ?? thread?.createdAt) ?? createdAt;
  return {
    id: thread?.id || '',
    sessionId: thread?.sessionId || thread?.id || '',
    title: thread?.name || thread?.preview || '未命名',
    preview: thread?.preview || '',
    cwd: thread?.cwd || WORK_DIR,
    model: thread?.modelProvider || '',
    createdAt,
    lastUsedAt,
    status: thread?.status || null,
    archived,
    source: 'app-server',
  };
}

function emitServerEnvelope(socket, type, payload) {
  socket.emit('agent:event', {
    seq: 0,
    epoch: 'server',
    sessionId: routeInstance(viewingInstanceId)?.sessionId ?? null,
    ts: Date.now(),
    type,
    payload,
  });
}

function appendAdminAudit(entry) {
  try {
    mkdirSync(DATA_DIR, { recursive: true, mode: 0o700 });
    const previous = existsSync(ADMIN_AUDIT_FILE) ? readFileSync(ADMIN_AUDIT_FILE, 'utf8') : '';
    writeOwnerOnlyFile(ADMIN_AUDIT_FILE, previous + JSON.stringify({ ts: Date.now(), ...entry }) + '\n');
  } catch {
    // Admin audit failures should not leak details or crash the socket handler.
  }
}

function adminSummary(action, payload = {}) {
  if (action === 'admin:configWrite') {
    return {
      keyPath: payload.keyPath || null,
      mergeStrategy: payload.mergeStrategy || null,
      filePath: payload.filePath ? sanitizePath(payload.filePath) : null,
    };
  }
  if (action === 'admin:configBatchWrite') {
    return {
      edits: Array.isArray(payload.edits) ? payload.edits.length : 0,
      keyPaths: Array.isArray(payload.edits) ? payload.edits.map(edit => edit?.keyPath).filter(Boolean).slice(0, 20) : [],
      filePath: payload.filePath ? sanitizePath(payload.filePath) : null,
    };
  }
  if (action === 'admin:pluginInstall') {
    return {
      pluginName: payload.pluginName || null,
      remoteMarketplaceName: payload.remoteMarketplaceName || null,
      marketplacePath: payload.marketplacePath ? sanitizePath(payload.marketplacePath) : null,
    };
  }
  if (action === 'admin:pluginUninstall') return { pluginId: payload.pluginId || null };
  if (action === 'admin:marketplaceAdd') return { source: payload.source || null, refName: payload.refName || null };
  if (action === 'admin:marketplaceRemove' || action === 'admin:marketplaceUpgrade') {
    return { marketplaceName: payload.marketplaceName || null };
  }
  if (action === 'admin:fsWriteFile') {
    return {
      path: payload.path ? sanitizePath(payload.path) : null,
      dataBase64: '<redacted>',
      approxBytes: typeof payload.dataBase64 === 'string' ? Math.floor(payload.dataBase64.length * 0.75) : 0,
    };
  }
  if (action === 'admin:fsRemove') {
    return { path: payload.path ? sanitizePath(payload.path) : null, recursive: payload.recursive, force: payload.force };
  }
  if (action === 'admin:fsCopy') {
    return {
      sourcePath: payload.sourcePath ? sanitizePath(payload.sourcePath) : null,
      destinationPath: payload.destinationPath ? sanitizePath(payload.destinationPath) : null,
      recursive: payload.recursive,
    };
  }
  if (action === 'admin:mcpToolCall') {
    return { server: payload.server || null, tool: payload.tool || null, arguments: '<redacted>' };
  }
  if (action === 'admin:accountLogout') return {};
  return {};
}

function denyAdmin(socket, ack, action, payload, error) {
  appendAdminAudit({
    event: 'denied',
    action,
    socketId: socket.id,
    error,
    summary: adminSummary(action, payload),
  });
  ackError(ack, new Error(error));
}

function requireAdmin(socket, ack, action, payload = {}) {
  if (socket.adminMode !== true) {
    denyAdmin(socket, ack, action, payload, 'Admin mode is locked');
    return false;
  }
  if (payload.adminConfirm !== action) {
    denyAdmin(socket, ack, action, payload, `Missing per-action confirm: ${action}`);
    return false;
  }
  return true;
}

async function runAdminAction(socket, ack, action, payload, operation) {
  if (!requireAdmin(socket, ack, action, payload)) return;
  try {
    const result = await operation();
    appendAdminAudit({
      event: 'success',
      action,
      socketId: socket.id,
      summary: adminSummary(action, payload),
    });
    ackOk(ack, { result: result ?? null });
  } catch (err) {
    appendAdminAudit({
      event: 'error',
      action,
      socketId: socket.id,
      error: err.message,
      summary: adminSummary(action, payload),
    });
    ackError(ack, err);
  }
}

// ---- Socket.IO 连接处理 ----
io.on('connection', socket => {
  console.log(`[conn] ${socket.id} 已连接（来自 ${clientIp(socket.handshake.address)}）`);

  if (socket.deviceApproved === false) {
    socket.emit('agent:event', {
      seq: 0, epoch: 'server', sessionId: null, ts: Date.now(),
      type: 'device_status', payload: { status: 'pending', deviceId: socket.handshake.auth?.deviceToken }
    });
  } else {
    // 已授权：发送初始状态
    const va = routeInstance(viewingInstanceId);
    socket.emit('agent:event', {
      seq: 0, epoch: 'server', sessionId: null, ts: Date.now(),
      type: 'init', payload: {
        sessionId: va?.sessionId ?? null,
        cwd: va?.cwd || WORK_DIR, workDirs, versions
      }
    });
    sendActiveStatus(socket, 'connect');
    sendSessionList(socket);
    socket.emit('agent:event', {
      seq: 0, epoch: 'server', sessionId: null, ts: Date.now(),
      type: 'pending_devices', payload: pendingDevicesPayload()
    });
    // 回放活跃会话缓冲
    if (va) {
      const { events } = va.eventsSince(0);
      for (const envelope of events) socket.emit('agent:event', envelope);
    }
  }

  on(socket, 'user:message', async payload => {
    const text = typeof payload === 'string' ? payload : payload?.text;
    const attachments = payload?.attachments;

    if ((!text || !text.trim()) && (!attachments || attachments.length === 0)) {
      return sysTo(socket, '消息为空或格式无效', true);
    }

    // 校验附件
    const attachErr = validateAttachments(attachments);
    if (attachErr) {
      return sysTo(socket, attachErr, true);
    }

    // 落盘附件
    let savedAttachments;
    if (attachments?.length) {
      try {
        savedAttachments = await saveAttachments(WORK_DIR, attachments);
      } catch (err) {
        return sysTo(socket, `附件保存失败：${err.message}`, true);
      }
    }

    if (text && text.length > 50000) {
      return sysTo(socket, `消息过长（${text.length} 字符，上限 50000），未发送`, true);
    }
    if (!routeInstance(viewingInstanceId)) {
      // 懒开：resume 当前 cwd 的最近会话，或新建
      const currentId = sessions.getCurrent(WORK_DIR);
      const agent = createAgent(currentId || null, WORK_DIR);
      viewingInstanceId = agent.instanceId;
    }
    const ai = routeInstance(viewingInstanceId);
    if (ai) await ai.send(text.trim(), savedAttachments);
  });

  on(socket, 'user:interrupt', () => {
    const ai = routeInstance(viewingInstanceId);
    if (ai?.busy) ai.abort();
  });

  // 手机端审批回传（仅 app-server 后端有 respondApproval）。
  on(socket, 'user:approval', payload => {
    const { approvalId, decision } = payload || {};
    const ai = routeInstance(viewingInstanceId);
    if (typeof ai?.respondApproval === 'function') {
      ai.respondApproval(approvalId, decision, payload);
    }
  });

  on(socket, 'account:loginStart', async (payload, ack) => {
    if (payload?.type && payload.type !== 'chatgptDeviceCode') {
      if (typeof ack === 'function') ack({ ok: false, error: '仅支持 chatgptDeviceCode 登录' });
      return;
    }
    let ai = routeInstance(viewingInstanceId);
    if (!ai) {
      ai = createAgent(null, WORK_DIR);
      viewingInstanceId = ai.instanceId;
      broadcastInstances();
    }
    if (typeof ai.startChatgptDeviceLogin !== 'function') {
      if (typeof ack === 'function') ack({ ok: false, error: '当前后端不支持 ChatGPT device code 登录' });
      return;
    }
    try {
      const response = await ai.startChatgptDeviceLogin();
      if (response?.type !== 'chatgptDeviceCode') throw new Error('account/login/start 未返回 device code');
      if (typeof ack === 'function') {
        ack({
          ok: true,
          loginId: response.loginId,
          verificationUrl: response.verificationUrl,
          userCode: response.userCode
        });
      }
    } catch (err) {
      const message = `登录启动失败：${err.message}`;
      if (typeof ack === 'function') ack({ ok: false, error: message });
      socket.emit('agent:event', {
        seq: 0, epoch: 'server', sessionId: ai.sessionId ?? null, ts: Date.now(),
        type: 'account_login', payload: { status: 'failed', error: message }
      });
    }
  });

  on(socket, 'account:loginCancel', async (payload, ack) => {
    const loginId = payload?.loginId;
    const ai = routeInstance(viewingInstanceId);
    if (!ai || typeof ai.cancelLogin !== 'function' || typeof loginId !== 'string' || !loginId) {
      if (typeof ack === 'function') ack({ ok: false, error: '无效登录任务' });
      return;
    }
    try {
      const response = await ai.cancelLogin(loginId);
      if (typeof ack === 'function') ack({ ok: true, status: response?.status || null });
    } catch (err) {
      const message = `登录取消失败：${err.message}`;
      if (typeof ack === 'function') ack({ ok: false, error: message });
      socket.emit('agent:event', {
        seq: 0, epoch: 'server', sessionId: ai.sessionId ?? null, ts: Date.now(),
        type: 'account_login', payload: { status: 'failed', loginId, error: message }
      });
    }
  });

  on(socket, 'thread:list', async (payload = {}, ack) => {
    try {
      const cwd = routeCwd(payload?.cwd);
      const ai = ensureControlAgent(cwd);
      const response = await ai.listThreads({
        cwd,
        archived: payload?.archived === true,
        limit: Number.isInteger(payload?.limit) ? payload.limit : 50,
        cursor: payload?.cursor,
        searchTerm: typeof payload?.searchTerm === 'string' ? payload.searchTerm : undefined,
      });
      ackOk(ack, {
        threads: (response?.data || []).map(thread => normalizeThread(thread, { archived: payload?.archived === true })),
        nextCursor: response?.nextCursor ?? null,
        backwardsCursor: response?.backwardsCursor ?? null,
        archived: payload?.archived === true,
      });
    } catch (err) {
      ackError(ack, err);
    }
  });

  on(socket, 'thread:select', async (payload = {}, ack) => {
    try {
      const threadId = payload?.threadId || payload?.sessionId;
      if (typeof threadId !== 'string' || !threadId) throw new Error('无效 threadId');
      const cwd = routeCwd(payload?.cwd);
      sessions.upsertSession({ id: threadId, title: payload?.title || threadId.slice(0, 8), cwd });
      const agent = createAgent(threadId, cwd);
      viewingInstanceId = agent.instanceId;
      broadcastInstances();
      io.emit('agent:event', {
        seq: 0, epoch: 'server', sessionId: threadId, ts: Date.now(),
        type: 'init', payload: { sessionId: threadId, cwd, workDirs, versions }
      });
      sendActiveStatus(socket, 'thread_select');
      ackOk(ack, { sessionId: threadId, instanceId: agent.instanceId });
    } catch (err) {
      ackError(ack, err);
    }
  });

  on(socket, 'thread:archive', async (payload = {}, ack) => {
    try {
      await ensureControlAgent(payload?.cwd).archiveThread(payload?.threadId);
      ackOk(ack, { threadId: payload?.threadId });
    } catch (err) {
      ackError(ack, err);
    }
  });

  on(socket, 'thread:unarchive', async (payload = {}, ack) => {
    try {
      await ensureControlAgent(payload?.cwd).unarchiveThread(payload?.threadId);
      ackOk(ack, { threadId: payload?.threadId });
    } catch (err) {
      ackError(ack, err);
    }
  });

  on(socket, 'thread:delete', async (payload = {}, ack) => {
    try {
      const threadId = payload?.threadId;
      await ensureControlAgent(payload?.cwd).deleteThread(threadId);
      for (const [instanceId, agent] of agents) {
        if (agent.sessionId === threadId) {
          agent.dispose();
          agents.delete(instanceId);
          if (viewingInstanceId === instanceId) viewingInstanceId = null;
        }
      }
      broadcastInstances();
      ackOk(ack, { threadId });
    } catch (err) {
      ackError(ack, err);
    }
  });

  on(socket, 'thread:rename', async (payload = {}, ack) => {
    try {
      await ensureControlAgent(payload?.cwd).renameThread(payload?.threadId, payload?.name);
      ackOk(ack, { threadId: payload?.threadId, name: String(payload?.name || '').trim() });
    } catch (err) {
      ackError(ack, err);
    }
  });

  on(socket, 'thread:compact', async (payload = {}, ack) => {
    try {
      await ensureControlAgent(payload?.cwd).compactThread(payload?.threadId);
      ackOk(ack, { threadId: payload?.threadId });
    } catch (err) {
      ackError(ack, err);
    }
  });

  on(socket, 'thread:rollback', async (payload = {}, ack) => {
    try {
      const response = await ensureControlAgent(payload?.cwd).rollbackThread({
        threadId: payload?.threadId,
        numTurns: payload?.numTurns,
      });
      emitServerEnvelope(socket, 'rollback', { threadId: payload?.threadId, numTurns: payload?.numTurns || 1 });
      ackOk(ack, { thread: response?.thread || null });
    } catch (err) {
      ackError(ack, err);
    }
  });

  on(socket, 'models:read', async (payload = {}, ack) => {
    try {
      const ai = ensureControlAgent(payload?.cwd);
      const [models, capabilities] = await Promise.all([
        ai.listModels({ includeHidden: payload?.includeHidden === true }),
        ai.readModelProviderCapabilities(),
      ]);
      ackOk(ack, { models: models?.data || [], nextCursor: models?.nextCursor ?? null, capabilities });
    } catch (err) {
      ackError(ack, err);
    }
  });

  on(socket, 'fs:readDirectory', async (payload = {}, ack) => {
    try {
      const response = await ensureControlAgent(payload?.cwd).readDirectory(payload?.path || WORK_DIR);
      ackOk(ack, { entries: response?.entries || [], path: payload?.path || WORK_DIR });
    } catch (err) {
      ackError(ack, err);
    }
  });

  on(socket, 'fs:readFile', async (payload = {}, ack) => {
    try {
      const response = await ensureControlAgent(payload?.cwd).readFile(payload?.path);
      ackOk(ack, { dataBase64: response?.dataBase64 || '', path: payload?.path });
    } catch (err) {
      ackError(ack, err);
    }
  });

  on(socket, 'account:read', async (payload = {}, ack) => {
    try {
      const ai = ensureControlAgent(payload?.cwd);
      const [account, usage, rateLimits] = await Promise.all([
        ai.readAccount(),
        ai.readUsage(),
        ai.readRateLimits(),
      ]);
      ackOk(ack, { account, usage, rateLimits });
    } catch (err) {
      ackError(ack, err);
    }
  });

  on(socket, 'mcp:read', async (payload = {}, ack) => {
    try {
      const response = await ensureControlAgent(payload?.cwd).listMcpServerStatus({ limit: payload?.limit || 50 });
      ackOk(ack, { servers: response?.data || [], nextCursor: response?.nextCursor ?? null });
    } catch (err) {
      ackError(ack, err);
    }
  });

  on(socket, 'skills:read', async (payload = {}, ack) => {
    try {
      const response = await ensureControlAgent(payload?.cwd).listSkills({ forceReload: payload?.forceReload === true });
      ackOk(ack, { entries: response?.data || [] });
    } catch (err) {
      ackError(ack, err);
    }
  });

  on(socket, 'externalAgentConfig:detect', async (payload = {}, ack) => {
    try {
      const response = await ensureControlAgent(payload?.cwd).detectExternalAgentConfig({
        includeHome: payload?.includeHome === true,
      });
      ackOk(ack, { items: response?.items || [] });
    } catch (err) {
      ackError(ack, err);
    }
  });

  on(socket, 'externalAgentConfig:import', async (payload = {}, ack) => {
    try {
      const items = Array.isArray(payload?.migrationItems) ? payload.migrationItems : [];
      if (!items.length) throw new Error('没有可导入的配置项');
      const response = await ensureControlAgent(payload?.cwd).importExternalAgentConfig(items, { source: 'mobile' });
      ackOk(ack, { importId: response?.importId || null });
    } catch (err) {
      ackError(ack, err);
    }
  });

  on(socket, 'p3:capabilities', async (payload = {}, ack) => {
    if (!requireP3Experimental(ack)) return;
    try {
      const response = await ensureControlAgent(payload?.cwd).listP3Capabilities();
      ackOk(ack, { capabilities: response?.data || response?.features || response || {} });
    } catch (err) {
      ackError(ack, err);
    }
  });

  on(socket, 'p3:terminalSpawn', async (payload = {}, ack) => {
    if (!requireP3Experimental(ack)) return;
    try {
      const processId = typeof payload?.processId === 'string' && payload.processId
        ? payload.processId
        : `term_${Date.now()}_${Math.random().toString(36).slice(2, 8)}`;
      const response = await ensureControlAgent(payload?.cwd).spawnTerminal({
        processId,
        command: Array.isArray(payload?.command) ? payload.command : [],
        cwd: payload?.cwd ? routeCwd(payload.cwd) : WORK_DIR,
        size: {
          cols: Number.isInteger(payload?.cols) ? payload.cols : 80,
          rows: Number.isInteger(payload?.rows) ? payload.rows : 24,
        },
      });
      ackOk(ack, { processId, result: response ?? null });
    } catch (err) {
      ackError(ack, err);
    }
  });

  on(socket, 'p3:terminalWrite', async (payload = {}, ack) => {
    if (!requireP3Experimental(ack)) return;
    try {
      await ensureControlAgent(payload?.cwd).writeTerminal(payload?.processId, payload?.text ?? '', {
        closeStdin: payload?.closeStdin === true,
      });
      ackOk(ack, { processId: payload?.processId });
    } catch (err) {
      ackError(ack, err);
    }
  });

  on(socket, 'p3:terminalResize', async (payload = {}, ack) => {
    if (!requireP3Experimental(ack)) return;
    try {
      await ensureControlAgent(payload?.cwd).resizeTerminal(payload?.processId, {
        cols: payload?.cols,
        rows: payload?.rows,
      });
      ackOk(ack, { processId: payload?.processId });
    } catch (err) {
      ackError(ack, err);
    }
  });

  on(socket, 'p3:terminalTerminate', async (payload = {}, ack) => {
    if (!requireP3Experimental(ack)) return;
    try {
      await ensureControlAgent(payload?.cwd).terminateTerminal(payload?.processId);
      ackOk(ack, { processId: payload?.processId });
    } catch (err) {
      ackError(ack, err);
    }
  });

  on(socket, 'p3:threadTurns', async (payload = {}, ack) => {
    if (!requireP3Experimental(ack)) return;
    try {
      const response = await ensureControlAgent(payload?.cwd).listThreadTurns({ threadId: payload?.threadId });
      ackOk(ack, response);
    } catch (err) {
      ackError(ack, err);
    }
  });

  on(socket, 'p3:threadSearch', async (payload = {}, ack) => {
    if (!requireP3Experimental(ack)) return;
    try {
      const response = await ensureControlAgent(payload?.cwd).searchThreads({
        query: payload?.query,
        limit: Number.isInteger(payload?.limit) ? payload.limit : 20,
        cursor: payload?.cursor,
        archived: payload?.archived === true,
      });
      ackOk(ack, response);
    } catch (err) {
      ackError(ack, err);
    }
  });

  on(socket, 'admin:unlock', async (payload = {}, ack) => {
    if (payload?.confirmText !== ADMIN_UNLOCK_PHRASE) {
      denyAdmin(socket, ack, 'admin:unlock', payload, 'Invalid admin unlock phrase');
      return;
    }
    socket.adminMode = true;
    appendAdminAudit({ event: 'unlock', action: 'admin:unlock', socketId: socket.id, summary: {} });
    ackOk(ack, { adminMode: true });
  });

  on(socket, 'admin:lock', async (_payload = {}, ack) => {
    socket.adminMode = false;
    appendAdminAudit({ event: 'lock', action: 'admin:lock', socketId: socket.id, summary: {} });
    ackOk(ack, { adminMode: false });
  });

  on(socket, 'admin:configWrite', async (payload = {}, ack) => {
    await runAdminAction(socket, ack, 'admin:configWrite', payload, () =>
      ensureControlAgent(payload?.cwd).writeConfigValue(payload));
  });

  on(socket, 'admin:configBatchWrite', async (payload = {}, ack) => {
    await runAdminAction(socket, ack, 'admin:configBatchWrite', payload, () =>
      ensureControlAgent(payload?.cwd).writeConfigBatch(payload));
  });

  on(socket, 'admin:pluginInstall', async (payload = {}, ack) => {
    await runAdminAction(socket, ack, 'admin:pluginInstall', payload, () =>
      ensureControlAgent(payload?.cwd).installPlugin(payload));
  });

  on(socket, 'admin:pluginUninstall', async (payload = {}, ack) => {
    await runAdminAction(socket, ack, 'admin:pluginUninstall', payload, () =>
      ensureControlAgent(payload?.cwd).uninstallPlugin(payload?.pluginId));
  });

  on(socket, 'admin:marketplaceAdd', async (payload = {}, ack) => {
    await runAdminAction(socket, ack, 'admin:marketplaceAdd', payload, () =>
      ensureControlAgent(payload?.cwd).marketplaceAdd(payload));
  });

  on(socket, 'admin:marketplaceRemove', async (payload = {}, ack) => {
    await runAdminAction(socket, ack, 'admin:marketplaceRemove', payload, () =>
      ensureControlAgent(payload?.cwd).marketplaceRemove(payload?.marketplaceName));
  });

  on(socket, 'admin:marketplaceUpgrade', async (payload = {}, ack) => {
    await runAdminAction(socket, ack, 'admin:marketplaceUpgrade', payload, () =>
      ensureControlAgent(payload?.cwd).marketplaceUpgrade(payload?.marketplaceName ?? null));
  });

  on(socket, 'admin:fsWriteFile', async (payload = {}, ack) => {
    await runAdminAction(socket, ack, 'admin:fsWriteFile', payload, () =>
      ensureControlAgent(payload?.cwd).writeFile(payload?.path, payload?.dataBase64));
  });

  on(socket, 'admin:fsRemove', async (payload = {}, ack) => {
    await runAdminAction(socket, ack, 'admin:fsRemove', payload, () =>
      ensureControlAgent(payload?.cwd).removePath(payload?.path, { recursive: payload?.recursive, force: payload?.force }));
  });

  on(socket, 'admin:fsCopy', async (payload = {}, ack) => {
    await runAdminAction(socket, ack, 'admin:fsCopy', payload, () =>
      ensureControlAgent(payload?.cwd).copyPath({
        sourcePath: payload?.sourcePath,
        destinationPath: payload?.destinationPath,
        recursive: payload?.recursive,
      }));
  });

  on(socket, 'admin:mcpToolCall', async (payload = {}, ack) => {
    await runAdminAction(socket, ack, 'admin:mcpToolCall', payload, () =>
      ensureControlAgent(payload?.cwd).callMcpTool({
        threadId: payload?.threadId,
        server: payload?.server,
        tool: payload?.tool,
        arguments: payload?.arguments,
        _meta: payload?._meta,
      }));
  });

  on(socket, 'admin:accountLogout', async (payload = {}, ack) => {
    await runAdminAction(socket, ack, 'admin:accountLogout', payload, () =>
      ensureControlAgent(payload?.cwd).logoutAccount());
  });

  on(socket, 'session:new', (payload, maybeAck) => {
    const ack = typeof payload === 'function' ? payload : maybeAck;
    const cwd = routeCwd(payload?.cwd);
    sessions.setCurrent(cwd, null);
    const agent = createAgent(null, cwd);
    viewingInstanceId = agent.instanceId;
    io.emit('agent:event', {
      seq: 0, epoch: 'server', sessionId: null, ts: Date.now(),
      type: 'init', payload: { sessionId: null, cwd, workDirs, versions }
    });
    sendSessionList(socket);
    broadcastInstances();
    if (typeof ack === 'function') ack({ ok: true });
  });

  on(socket, 'session:list', async (payload, maybeAck) => {
    const ack = typeof payload === 'function' ? payload : maybeAck;
    if (typeof ack !== 'function') {
      // 推送到 socket（合并 sessions.json + Codex 原生会话）
      try {
        const allSessions = sessions.getState().sessions.filter(s => s.cwd === WORK_DIR);
        const currentId = sessions.getCurrent(WORK_DIR);
        const codexSessions = await listCodexSessions(WORK_DIR, { limit: 50 });
        socket.emit('agent:event', {
          seq: 0, epoch: 'server', sessionId: null, ts: Date.now(),
          type: 'session_list',
          payload: { sessions: allSessions, codexSessions, currentSessionId: currentId }
        });
      } catch (err) {
        sendSessionList(socket);
      }
      return;
    }
    try {
      const allSessions = sessions.getState().sessions.filter(s => s.cwd === WORK_DIR);
      const currentId = sessions.getCurrent(WORK_DIR);
      const codexSessions = await listCodexSessions(WORK_DIR, { limit: 50 });
      ack({ sessions: allSessions, codexSessions, currentSessionId: currentId });
    } catch (err) {
      const allSessions = sessions.getState().sessions.filter(s => s.cwd === WORK_DIR);
      const currentId = sessions.getCurrent(WORK_DIR);
      ack({ sessions: allSessions, currentSessionId: currentId });
    }
  });

  on(socket, 'session:select', (payload, ack) => {
    const sessionId = payload?.sessionId || payload;
    if (typeof sessionId !== 'string') {
      if (typeof ack === 'function') ack({ ok: false, error: '无效会话 ID' });
      return;
    }
    const sess = sessions.getSession(sessionId);
    if (!sess) {
      if (typeof ack === 'function') ack({ ok: false, error: '会话不存在' });
      return;
    }
    sessions.setCurrent(WORK_DIR, sessionId);
    const agent = createAgent(sessionId, WORK_DIR);
    viewingInstanceId = agent.instanceId;
    broadcastInstances();
    io.emit('agent:event', {
      seq: 0, epoch: 'server', sessionId: null, ts: Date.now(),
      type: 'init', payload: { sessionId, cwd: WORK_DIR, workDirs, versions }
    });
    sendActiveStatus(socket, 'session_select');
    sendSessionList(socket);
    if (typeof ack === 'function') ack({ ok: true, sessionId });
  });

  on(socket, 'session:fork', async (payload, ack) => {
    const ai = routeInstance(payload?.instanceId || viewingInstanceId);
    const threadId = typeof payload?.threadId === 'string' && payload.threadId
      ? payload.threadId
      : ai?.sessionId;
    if (!ai || !threadId || typeof ai.forkThread !== 'function') {
      if (typeof ack === 'function') ack({ ok: false, error: '当前没有可分叉的会话' });
      else sysTo(socket, '当前没有可分叉的会话', true);
      return;
    }

    try {
      const response = await ai.forkThread({
        threadId,
        ephemeral: payload?.ephemeral === true
      });
      const sessionId = forkedSessionId(response);
      if (!sessionId) throw new Error('thread/fork 未返回 thread.id');
      const cwd = ai.cwd || WORK_DIR;
      sessions.upsertSession({ id: sessionId, title: payload?.title || `Fork ${String(threadId).slice(0, 8)}`, cwd });
      const agent = createAgent(sessionId, cwd);
      viewingInstanceId = agent.instanceId;
      io.emit('agent:event', {
        seq: 0, epoch: 'server', sessionId, ts: Date.now(),
        type: 'init', payload: { sessionId, cwd, workDirs, versions }
      });
      broadcastInstances();
      broadcastSessionList(cwd);
      sendActiveStatus(socket, 'session_fork');
      if (typeof ack === 'function') ack({ ok: true, sessionId, instanceId: agent.instanceId });
    } catch (err) {
      const message = `会话分叉失败：${err.message}`;
      if (typeof ack === 'function') ack({ ok: false, error: message });
      socket.emit('agent:event', {
        seq: 0, epoch: 'server', sessionId: ai.sessionId ?? null, ts: Date.now(),
        type: 'error', payload: { message, recoverable: true }
      });
    }
  });

  on(socket, 'session:switch', payload => {
    const iid = payload?.instanceId;
    if (agents.has(iid)) {
      viewingInstanceId = iid;
      broadcastInstances();
    }
  });

  on(socket, 'session:history', async (payload, ack) => {
    const sessionId = typeof payload === 'string' ? payload : payload?.sessionId;
    if (!sessionId || typeof sessionId !== 'string') {
      if (typeof ack === 'function') ack({ messages: [] });
      return;
    }
    try {
      // 从 history.js 查找会话文件路径
      const sessions = await listCodexSessions(WORK_DIR, { limit: 100 });
      const found = sessions.find(s => s.id === sessionId);
      if (!found?.filePath) {
        if (typeof ack === 'function') ack({ messages: [] });
        return;
      }
      const msgs = await getSessionHistory(found.filePath, 100);
      if (typeof ack === 'function') ack({ messages: msgs, title: found.title });
    } catch (err) {
      console.error('[history] 读取失败:', err.message);
      if (typeof ack === 'function') ack({ messages: [] });
    }
  });

  on(socket, 'catch-up', (payload, ack) => {
    const { sessionId, lastSeq } = payload || {};
    if (typeof ack !== 'function') return;
    const ai = routeInstance(resolveInstanceId(sessionId));
    if (!ai || ai.sessionId !== sessionId) {
      return ack({ replayed: 0, gap: false });
    }
    const { events, gap } = ai.eventsSince(Number(lastSeq) || 0);
    for (const envelope of events) socket.emit('agent:event', envelope);
    ack({ replayed: events.length, gap: Boolean(gap) });
  });

  // 已信任设备远程审批待批设备
  on(socket, 'user:approveDevice', payload => {
    const deviceId = payload?.deviceId;
    if (typeof deviceId !== 'string' || !deviceId) return;
    if (!getPendingDevices().some(d => d.deviceToken === deviceId)) return;
    approveDevice(deviceId);
    unlockDeviceSockets(deviceId);
    broadcastPendingDevices();
  });

  on(socket, 'user:denyDevice', payload => {
    const deviceId = payload?.deviceId;
    if (typeof deviceId !== 'string' || !deviceId) return;
    denyDevice(deviceId);
    disconnectDeviceSockets(deviceId);
    broadcastPendingDevices();
  });

  socket.on('disconnect', reason => {
    console.log(`[conn] ${socket.id} 已断开（${reason}）`);
  });
});

// ---- 状态栏刷新 ----
let statusRefreshTimer = null;
let pruneUploadsTimer = null;

async function refreshStatusLine() {
  try {
    const payload = await buildStatusLine({
      agent: routeInstance(viewingInstanceId),
      cwd: WORK_DIR,
      versions
    });
    io.emit('agent:event', {
      seq: 0, epoch: 'server', sessionId: routeInstance(viewingInstanceId)?.sessionId ?? null, ts: Date.now(),
      type: 'status_line', payload
    });
  } catch (err) {
    console.error('[statusline] 刷新失败:', err.message);
  }
}

function scheduleStatusRefresh() {
  clearInterval(statusRefreshTimer);
  statusRefreshTimer = setInterval(refreshStatusLine, 4_000);
  refreshStatusLine(); // 立即刷新一次
}

// ---- 启动 ----
export function startServer() {
  if (workDirs.length === 0) initializeWorkDirs();
  httpServer.listen(PORT, HOST, () => {
    const displayHost = HOST === '0.0.0.0' ? 'localhost' : HOST;
    const address = httpServer.address();
    const displayPort = typeof address === 'object' && address ? address.port : PORT;
    console.log(`🚀 Codex Chat Mobile 运行在 http://${displayHost}:${displayPort}`);
    scheduleStatusRefresh();

    // 启动时清理过期附件
    for (const dir of workDirs) {
      pruneExpiredUploads(dir).catch(() => {});
    }

    // 每 1 小时自动定时清理
    pruneUploadsTimer = setInterval(() => {
      for (const dir of workDirs) {
        pruneExpiredUploads(dir).catch(() => {});
      }
    }, 3600000);
    pruneUploadsTimer.unref?.();
  });
  return httpServer;
}

export function stopServer(callback) {
  clearInterval(statusRefreshTimer);
  statusRefreshTimer = null;
  clearInterval(pruneUploadsTimer);
  pruneUploadsTimer = null;
  for (const agent of agents.values()) {
    try { agent.dispose?.(); } catch { /* noop */ }
  }
  agents.clear();
  viewingInstanceId = null;
  if (!httpServer.listening) {
    callback?.();
    return;
  }
  httpServer.close(callback);
}

if (shouldStartServer) startServer();

// 优雅退出
function shutdown() {
  console.log('\n[server] 正在关闭...');
  try { sessions.flushSaveSync(); } catch { /* noop */ }
  process.exit(0);
}
if (shouldStartServer) {
  process.on('SIGTERM', shutdown);
  process.on('SIGINT', shutdown);
}
