// ── 全书结构 + 阅读顺序的唯一事实来源 ──────────────────────────────
// codex-chat-mobile 项目全景手册
module.exports = {
  title: 'Codex Chat Mobile',
  subtitle: '项目全景手册',
  tagline: '本地 Codex CLI 的移动端控制面',
  repo: 'Ike-li/codex-chat-mobile',
  version: '手册 v1.0',
  parts: [
    {
      id: 'p0', label: '起点', icon: '◆',
      desc: '先到这里，拿到全局视角与阅读路线。',
      pages: [
        { slug: 'index', title: '封面与导读', home: true, time: 5,
          lead: '一句话认识项目，看清这本手册怎么读。' },
        { slug: 'reading-guide', title: '阅读顺序指南', time: 10,
          lead: '三条阅读路线：速览、完整通读、按角色切入。' },
      ],
    },
    {
      id: 'p1', label: '第一部分 · 认识项目', icon: '01',
      desc: '它是什么、为谁服务、边界在哪里。',
      pages: [
        { slug: 'overview', title: '项目总览', time: 10,
          lead: '定位、核心理念，在更大系统中的位置。',
          src: ['README.md', 'CLAUDE.md'] },
        { slug: 'architecture', title: '系统架构总览', time: 14,
          lead: '分层架构、技术栈，一条数据如何流经整个系统。',
          src: ['docs/ARCHITECTURE.md'] },
        { slug: 'boundaries', title: '职责边界与生态', time: 8,
          lead: '各模块如何分工，不可逾越的职责铁律。',
          src: ['docs/ARCHITECTURE.md', 'SECURITY.md'] },
      ],
    },
    {
      id: 'p2', label: '第二部分 · 演进历程', icon: '02',
      desc: '理解今天的架构，先看清它从哪里来。',
      pages: [
        { slug: 'evolution', title: '架构演进主线', time: 12,
          lead: '关键决策点，每个阶段解决了什么问题。',
          src: ['ROADMAP.md', 'git log'] },
        { slug: 'protocol-model', title: '协议模型演进', time: 10,
          lead: '从 codex exec 到 app-server 的转变。',
          src: ['docs/PROTOCOL.md'] },
      ],
    },
    {
      id: 'p3', label: '第三部分 · 方法论', icon: '03',
      desc: '平台背后的思维模型。',
      pages: [
        { slug: 'tdd-methodology', title: 'TDD 开发方法论', time: 12,
          lead: '测试驱动开发在本项目中的实践。',
          src: ['CLAUDE.md', 'docs/TESTING.md'] },
        { slug: 'protocol-design', title: '协议设计哲学', time: 10,
          lead: '宽容策略、降级兜底、未知容错。',
          src: ['docs/PROTOCOL.md'] },
        { slug: 'glossary', title: '术语表', time: 6,
          lead: '高频专有名词的准确定义。',
          src: ['docs/'] },
      ],
    },
    {
      id: 'p4', label: '第四部分 · 核心实现', icon: '04',
      desc: '逐个拆解系统的主要能力。',
      pages: [
        { slug: 'capabilities-overview', title: '能力总览', time: 8,
          lead: '一张表看清所有核心能力。',
          src: ['docs/API.md'] },
        { slug: 'session-lifecycle', title: '会话生命周期', time: 14,
          lead: 'initialize → thread → turn 的完整流程。',
          src: ['agent-appserver.js'] },
        { slug: 'approval-system', title: '审批系统', time: 12,
          lead: '命令/文件/权限审批的分类与决议。',
          src: ['approval-broker.js', 'docs/API.md'] },
        { slug: 'streaming-events', title: '流式事件处理', time: 12,
          lead: '从 app-server 通知到前端渲染的数据流。',
          src: ['agent-appserver.js', 'server.js'] },
        { slug: 'file-upload', title: '文件上传与安全', time: 10,
          lead: '校验、限量、owner-only 落盘。',
          src: ['uploads.js', 'file-security.js'] },
        { slug: 'multi-instance', title: '多实例与工作区', time: 10,
          lead: '多标签隔离、多工作目录路由。',
          src: ['server.js'] },
      ],
    },
    {
      id: 'p5', label: '第五部分 · 数据与集成', icon: '05',
      desc: '数据从哪来、存哪去、和谁对接。',
      pages: [
        { slug: 'data-flow', title: '数据流全景', time: 10,
          lead: '从浏览器到 app-server 的四条主链路。',
          src: ['docs/ARCHITECTURE.md', 'docs/API.md'] },
        { slug: 'protocol-integration', title: 'Codex 协议集成', time: 12,
          lead: 'JSON-RPC 2.0 over stdio 的实现细节。',
          src: ['docs/PROTOCOL.md', 'agent-appserver.js'] },
        { slug: 'socket-io-api', title: 'Socket.IO 接口层', time: 10,
          lead: '客户端可调用的事件签名与信封格式。',
          src: ['docs/API.md', 'server.js'] },
      ],
    },
    {
      id: 'p6', label: '第六部分 · 部署与运维', icon: '06',
      desc: '怎么把它跑起来、跑稳。',
      pages: [
        { slug: 'quickstart', title: '快速开始', time: 10,
          lead: '本地起一套的最短路径。',
          src: ['README.md', 'docs/GUIDE.md'] },
        { slug: 'remote-access', title: '远程访问方案', time: 12,
          lead: 'HTTPS/PWA/Push 的硬限制与解决方案。',
          src: ['docs/REMOTE_ACCESS.md'] },
        { slug: 'security-model', title: '安全模型', time: 10,
          lead: 'AUTH_TOKEN、设备信任、loopback 规则。',
          src: ['SECURITY.md', 'docs/ARCHITECTURE.md'] },
        { slug: 'testing', title: '测试体系', time: 10,
          lead: '四道门禁、验收矩阵、手工冒烟清单。',
          src: ['docs/TESTING.md'] },
      ],
    },
    {
      id: 'p7', label: '第七部分 · 参考与规范', icon: '07',
      desc: '规范、约定、避坑指南。',
      pages: [
        { slug: 'project-rules', title: '项目规范', time: 8,
          lead: '开发与文档约定。',
          src: ['CLAUDE.md', 'CONTRIBUTING.md'] },
        { slug: 'api-reference', title: '接口参考速查', time: 10,
          lead: 'HTTP 路由 + Socket.IO 事件完整签名。',
          src: ['docs/API.md'] },
        { slug: 'protocol-reference', title: '协议参考速查', time: 10,
          lead: 'app-server 方法清单与覆盖情况。',
          src: ['docs/PROTOCOL.md'] },
        { slug: 'drift', title: '漂移清单', time: 8,
          lead: '文档与代码不一致的地方，接手必读。',
          src: ['代码与文档交叉核对'] },
      ],
    },
  ],
};
